- src/com/magento/idea/magento2plugin/completion/provider/FilePathCompletionProvider.java
- src/com/magento/idea/magento2plugin/util/VfsUtil.java
Fixes https://github.com/magento/magento2-phpstorm-plugin/issues/8
> ISSUE-8: NullPointerException

- META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/completion/provider/mftf/ActionGroupCompletionProvider.java
- src/com/magento/idea/magento2plugin/completion/provider/mftf/DataCompletionProvider.java
- src/com/magento/idea/magento2plugin/completion/provider/mftf/SelectorCompletionProvider.java
- src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
- src/com/magento/idea/magento2plugin/reference/provider/mftf/ActionGroupReferenceProvider.java
- src/com/magento/idea/magento2plugin/reference/provider/mftf/DataReferenceProvider.java
- src/com/magento/idea/magento2plugin/reference/provider/mftf/PageReferenceProvider.java
- src/com/magento/idea/magento2plugin/reference/provider/mftf/SectionReferenceProvider.java
- src/com/magento/idea/magento2plugin/reference/provider/mftf/VariableToStepKeyProvider.java
- src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
- src/com/magento/idea/magento2plugin/stubs/indexes/mftf/ActionGroupIndex.java
- src/com/magento/idea/magento2plugin/stubs/indexes/mftf/DataIndex.java
- src/com/magento/idea/magento2plugin/stubs/indexes/mftf/PageIndex.java
- src/com/magento/idea/magento2plugin/stubs/indexes/mftf/SectionIndex.java
- src/com/magento/idea/magento2plugin/stubs/indexes/mftf/StepKeyIndex.java
Should be a minor version increase.
> Add partial MFTF support (autocomplete/navigation)

- META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/project/ProjectDetector.java
Major version update.
Fixed incompatibility in `com.magento.idea.magento2plugin.project.ProjectDetector#configureProject`.
> Increasing module version to support 2020.* IDE's, removed usage of the deprecated method

- .phpstorm.meta.php/di-autocomplete.php
- META-INF/plugin.xml
> [WIP] Adds PhpStorm's meta plugin file

- src/com/magento/idea/magento2plugin/reference/provider/mftf/PageReferenceProvider.java
This PR fixes the running IDE issue, because of not uninstalled packages. The removed packages aren't used anymore. 
N/A
> Removing the not used packages that breaking the running IDE

- resources/fileTemplates/code/Magento Module DI Xml Plugin.xml.html
This PR adds the description for the `Magento Module DI Xml Plugin.xml` template.
1. magento/magento2-phpstorm-plugin#88: Code generation. di.xml plugin template description
N/A
> Added the short description for the plugin di.xml template

- resources/fileTemplates/internal/Magento Php Preference Class.php.html
This PR adds the description for the `Magento Php Preference Class.php.ft` template.
1. magento/magento2-phpstorm-plugin#86: Code generation. PHP preference template description
N/A
> Add the description for PHP preference class template

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
- src/com/magento/idea/magento2plugin/project/Settings.java
- src/com/magento/idea/magento2plugin/project/SettingsForm.form
- src/com/magento/idea/magento2plugin/project/SettingsForm.java
This PR moves the custom license default text from the "New Module Dialog" to the project's settings
N/A
N/A
> Added the module's default license name at the project settings level

- resources/fileTemplates/internal/Magento Module Events Xml.xml.html
This PR adds the description for the `Magento Module Events Xml.xml.ft` template.
N/A
> Add description for the module events.xml template

- resources/fileTemplates/internal/Magento Observer Class.php.ft
- resources/fileTemplates/internal/Magento Observer Class.php.html
This PR adds the required method implementation `execute` for an observer class to the template
and enriched with the description.
N/A
N/A
> Added the observer's template must-have implemented method and template description

- resources/fileTemplates/code/Magento Module Events Xml Observer.xml.html
- resources/fileTemplates/code/Magento Observer Execute Method.php.html
This PR adds description for observer templates:
- Magento Observer Execute Method.php
- Magento Module Events Xml Observer.xml
> description for observer templates

- resources/inspectionDescriptions/PluginDeclarationInspection.html
This PR adds an inspection description for the `Duplicated Plugin Usage in di XML` inspection.
#167 
N/A
> 167: Add the Duplicated Plugin Usage in di XML inspection description

- src/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverEventsXmlGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
- testData/actions/generation/generator/CronjobClassGenerator/generateFile/CleanTableCronjob.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/CronjobClassGeneratorTest.java
Added test coverage for the Cron job generator. This should be used as an example for other generators.
> Covered Cron Job Generator by an Integration test

- src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
- src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.java
- src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
- src/com/magento/idea/magento2plugin/magento/packages/File.java
- src/com/magento/idea/magento2plugin/util/magento/FileBasedIndexUtil.java
- src/com/magento/idea/magento2plugin/util/magento/MagentoVersion.java
- tests/com/magento/idea/magento2plugin/BaseProjectTestCase.java
- tests/com/magento/idea/magento2plugin/completion/xml/CompletionXmlFixtureTestCase.java
- tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java
- tests/com/magento/idea/magento2plugin/inspections/xml/InspectionXmlFixtureTestCase.java
- tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
- tests/com/magento/idea/magento2plugin/linemarker/php/LinemarkerPhpFixtureTestCase.java
- tests/com/magento/idea/magento2plugin/reference/php/ReferencePhpFixtureTestCase.java
- tests/com/magento/idea/magento2plugin/reference/xml/ReferenceXmlFixtureTestCase.java
Forward port for #207 Implemented custom file separator, utilize java.io.File breaks Windows
> Forward port custom file separator [207]

- .github/workflows/gradlepublish.yml
- CHANGELOG.md
- build.gradle
Added workflow to publish plugin when release is created.
1. #42: Infrastructure. Configure Gradle to publish a tag automatically to JetBrains repo
> Added publish plugin configuration

- testData/actions/generation/generator/ModuleXmlGenerator/generateFileInRoot/module.xml
- testData/actions/generation/generator/ModuleXmlGenerator/generateModuleFile/module.xml
- tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleXmlGeneratorTest.java
Added test coverage to module.xml generator
1. magento/magento2-phpstorm-plugin#190: Integration tests: cover module xml generator
> Covered module.xml generator by test

- testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json
- testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json
- tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
Covered module composer.json generator by tests
1. magento/magento2-phpstorm-plugin#195: Integration tests: cover module composer.json generator
> Cover composer.json generator by tests

- .github/workflows/gradlepublishalpha.yml
- build.gradle
- resources/META-INF/plugin.xml
Added workflow to deploy alpha version to the JetBrains according to the documentation https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html#specifying-a-release-channel
> Added a publish alpha version workflow of the plugin to the JetBrains repo

- resources/fileTemplates/internal/Magento Module DI Xml.xml.html
Add di.xml template description
1. magento/magento2-phpstorm-plugin#85
> Add di.xml template description

- testData/actions/generation/generator/PluginClassGenerator/generatePluginClassFile/TestPlugin.php
- testData/project/magento2/app/code/Foo/Bar/Service/SimpleService.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGeneratorTest.java
This PR adds test coverage for `com.magento.idea.magento2plugin.actions.generation.generator.PluginClassGenerator` generator.
1. magento/magento2-phpstorm-plugin#201: Integration tests: cover plugin class generator
> #issue-201 Covered Plugin Class generator

- testData/completion/xml/LayoutBlockCompletionRegistrar/referenceBlockMustHaveCompletion/default.xml
- testData/project/magento2/vendor/magento/module-catalog/view/frontend/layout/test_index_index.xml
- testData/reference/xml/LayoutBlockReferenceRegistrar/referenceBlockMustHaveReference/default.xml
- tests/com/magento/idea/magento2plugin/completion/xml/LayoutBlockCompletionRegistrarTest.java
- tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java
- tests/com/magento/idea/magento2plugin/reference/xml/LayoutBlockReferenceRegistrarTest.java
This PR covers reference block name attribute completion and reference by functional.
> Covered reference block related functionality with tests

- testData/completion/xml/LayoutUpdateHandleCompletionRegistrar/updateHandleMustHaveCompletion/test_test_test.xml
- testData/project/magento2/vendor/magento/module-catalog/view/frontend/layout/test_index_index2.xml
- testData/reference/xml/LayoutUpdateHandleReferenceRegistrar/layoutUpdateHandleMustHaveReference/test_test_test.xml
- tests/com/magento/idea/magento2plugin/completion/xml/LayoutUpdateHandleCompletionRegistrarTest.java
- tests/com/magento/idea/magento2plugin/reference/xml/LayoutUpdateHandleReferenceRegistrarTest.java
This PR covers completion and reference of the `handle` XML attribute of the layout XML file by functional tests.
> Added test coverage for the layout update handle

- testData/actions/generation/generator/CrontabXmlGenerator/addTwoCronJobsToDifferentCronTabs/crontab.xml
- testData/actions/generation/generator/CrontabXmlGenerator/addTwoCronJobsToOneCronTab/crontab.xml
- testData/actions/generation/generator/CrontabXmlGenerator/generateCronTabXmlFileWithSchedule/crontab.xml
- testData/actions/generation/generator/CrontabXmlGenerator/generateCronTabXmlFileWithScheduleConfig/crontab.xml
- tests/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGeneratorTest.java
This PR covers [`com.magento.idea.magento2plugin.actions.generation.generator.com.magento.idea.magento2plugin.actions.generation.generator`](https://github.com/magento/magento2-phpstorm-plugin/blob/1.0.1-develop/src/com/magento/idea/magento2plugin/actions/generation/generator/CrontabXmlGenerator.java) with tests.
N/A
> Covered CrontabXmlGenerator by tests

- .github/workflows/gradle.yml
- build.gradle
- resources/META-INF/plugin.xml
Initial PR for 1.0.2, contains version encreasing in all needed places.
> Initial PR for 1.0.2

- gradle-tasks/pmd/ruleset.xml
- resources/META-INF/plugin.xml
- resources/fileTemplates/code/Magento Module Class Arguments In Xml.php.html
- resources/fileTemplates/code/Magento Module Class Arguments In Xml.xml.ft
- src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/InjectAViewModelDialogValidator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/code/ClassArgumentInXmlConfigGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/CommonXml.java
- src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java
- src/com/magento/idea/magento2plugin/magento/packages/XsiTypes.java
- src/com/magento/idea/magento2plugin/util/FirstLetterToLowercaseUtil.java
This PR introduces functionality for injecting a view model to a block.
> Inject a view model to a block and a reference block from the context menu

- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
- src/com/magento/idea/magento2plugin/util/CamelCaseToHyphen.java
[#263]_package name in composer.json is missing the first letter
1, Fix missing first letter name in composer.json
2, Check the unit test
Please review my code and merge the code. Thanks!
> [#263]_package name in composer.json is missing the first letter

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Module ACL XML.xml.ft
- resources/fileTemplates/internal/Magento Module ACL XML.xml.html
- src/com/magento/idea/magento2plugin/actions/generation/data/AclXmlData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateAclXml.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleAclXml.java
- src/com/magento/idea/magento2plugin/util/magento/GetAclResourcesListUtil.java
- src/com/magento/idea/magento2plugin/util/magento/GetAclResourcesTreeUtil.java
- src/com/magento/idea/magento2plugin/util/xml/XmlPsiTreeUtil.java
- testData/actions/generation/generator/AclXmlGenerator/generateAclXmlFile/acl.xml
- testData/actions/generation/generator/AclXmlGenerator/generateAclXmlFileForNonExistedParent/acl.xml
- testData/actions/generation/generator/AclXmlGenerator/getAclXmlFileAndGenerateNewAcl/acl.xml
- testData/project/magento2/vendor/magento/module-backend/etc/acl.xml
- testData/project/magento2/vendor/magento/module-config/composer.json
- testData/project/magento2/vendor/magento/module-config/etc/acl.xml
- testData/project/magento2/vendor/magento/module-config/etc/module.xml
- testData/project/magento2/vendor/magento/module-config/registration.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/AclXmlGeneratorTest.java
**Description (*)**
This PR extends the new UI component form generation functionality with the generation of ACL resources XML file.
> Generated ACL in scope of ui component form generation

- src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java
- src/com/magento/idea/magento2plugin/reference/provider/PhpJobMethodReferenceProvider.java
- src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
- testData/completion/xml/CrontabCompletionRegistrar/cronJobInstanceMustHaveCompletion/crontab.xml
- testData/completion/xml/CrontabCompletionRegistrar/cronJobMethodMustHaveCompletion/crontab.xml
- testData/completion/xml/CrontabCompletionRegistrar/notCrontabXmlMethodMustHaveNotCompletion/wrong_named_crontab.xml
- testData/completion/xml/CrontabCompletionRegistrar/notCrontabXmlMustHaveNotCompletion/wrong_named_crontab.xml
- testData/completion/xml/CrontabCompletionRegistrar/notInstanceAttrMustHaveNotCompletion/crontab.xml
- testData/completion/xml/CrontabCompletionRegistrar/notJobTagMustHaveNotCompletion/crontab.xml
- testData/project/magento2/vendor/magento/module-catalog/Cron/RefreshSpecialPrices.php
- testData/reference/xml/CrontabReferenceRegistrar/crontabInstanceMustHaveReference/crontab.xml
- testData/reference/xml/CrontabReferenceRegistrar/crontabMethodMustHaveReference/crontab.xml
- tests/com/magento/idea/magento2plugin/completion/xml/CrontabCompletionRegistrarTest.java
- tests/com/magento/idea/magento2plugin/reference/xml/CrontabReferenceRegistrarTest.java
**Description (*)**
This PR adds test coverage to references and completions of crontab instance and method attributes. Related PR: #280   
> Added test coverage for references and completions of crontab instance and method

- .github/workflows/gradle.yml
- build.gradle
- resources/META-INF/plugin.xml
> 2.0.1-develop initial

- CHANGELOG.md
- build.gradle
* Improved Changelog to be compatible with https://keepachangelog.com/en/1.0.0
* added recent changes to Changelog
> Updated changelog

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
This PR fixes couple of issues related to Ui form generation
1. magento/magento2-phpstorm-plugin#<issue_number>: Issue title
> Fixing name column

- .github/workflows/gradle.yml
1. magento/magento2-phpstorm-plugin#<issue_number>: Issue title
> Add gradle cache to speed up builds

- CHANGELOG.md
- src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
Fix for the override in theme action.
Corrected directories generation.
> Fixed directory structure for the override in theme action

- resources/META-INF/plugin.xml
Removed residue code caused by PR https://github.com/magento/magento2-phpstorm-plugin/pull/281
1. Fixes magento/magento2-phpstorm-plugin#375: Can't find template Magento Module Ui Grid Collection Data Provider Php
> Removed residue code

- CHANGELOG.md
> Adjusted CHANGELOG.md for 2.0.2 patch release

- CHANGELOG.md
Updated `CHANGELOG.md` for upcoming release `v2.1.0`
> Updated CHANGELOG.md for 2.1.0 release

- testData/inspections/php/PluginInspection/withWrongCallableType/Plugin.php
- testData/inspections/php/PluginInspection/withWrongParameterType/Plugin.php
- tests/com/magento/idea/magento2plugin/inspections/php/PluginInspectionTest.java
Added test coverage for `PluginInspection`
> Added test coverage for PluginInspection

- resources/fileTemplates/internal/Magento Form Button Block Class.php.html
- resources/fileTemplates/internal/Magento UI Component Form XML.xml.html
Fixed incorrect template content
> Fixed incorrect file template content

- resources/fileTemplates/internal/Magento Resource Model Class.php.html
In this PR I've added description for the internal file template **Magento Resource Model Class**.
> Added template description for Magento Resource Model Class

- .github/workflows/gradlepublish.yml
- .github/workflows/gradlepublishalpha.yml
> Fix publishing

- CHANGELOG.md
- README.md
- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/stubs/indexes/xml/PhpClassNameIndex.java
Skipping IDEA tags during indexing that causing errors. 
Covered child tags case.
To reproduce run reindex via module config.
1. Fixes magento/magento2-phpstorm-plugin#410
> Skip IDEA include tag

- .github/workflows/gradle.yml
- .github/workflows/gradlepublish.yml
- .github/workflows/gradlepublishalpha.yml
- CHANGELOG.md
- build.gradle
- resources/META-INF/plugin.xml
> 3.0.1 ->3.1.0 forwardport

- CHANGELOG.md
- resources/magento2/common.properties
Restored missing bundle message
1. Fixes magento/magento2-phpstorm-plugin#420
> #420 Fixed the Inject a ViewModel dialog

- resources/magento2/validation.properties
- src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithColonRule.java
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
Backport of https://github.com/magento/magento2-phpstorm-plugin/pull/429
> Backport of PR#429

- src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Backport of https://github.com/magento/magento2-phpstorm-plugin/pull/435
> Fixed NPTR exception in theme directory view model action

- CHANGELOG.md
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
- src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
> 3.0.3 develop >3.1.0 develop forwardport

- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInTheme.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
[#444]_Add options for an override and extend the layout
The function wanna like:
Thanks.
> [#444]_Add options for override and extend layout

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Module Declarative Schema Whitelist JSON.json.ft
- resources/fileTemplates/internal/Magento Module Declarative Schema Whitelist JSON.json.html
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistJsonGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDbSchemaWhitelistJson.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaWhitelistJson.java
- testData/actions/generation/generator/DbSchemaWhitelistGenerator/generateDbSchemaWhitelistJsonFile/db_schema_whitelist.json
- tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistGeneratorTest.java
Added db_schema_whitelist.json file generation and test coverage for its generator.
**Testing in the local env:**
**Resulting file:**
> 309 add db schema whitelist generation

- src/com/magento/idea/magento2plugin/actions/generation/data/DbSchemaXmlData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistJsonGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/DbSchemaGeneratorUtil.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleDbSchemaXml.java
- src/com/magento/idea/magento2plugin/magento/packages/PropertiesTypes.java
- src/com/magento/idea/magento2plugin/magento/packages/database/ColumnAttributes.java
- src/com/magento/idea/magento2plugin/magento/packages/database/PropertyToDefaultTypeMapperUtil.java
- src/com/magento/idea/magento2plugin/reference/provider/TableColumnNamesReferenceProvider.java
- testData/actions/generation/generator/DbSchemaWhitelistGenerator/generateDbSchemaWhitelistJsonFileForShortProperties/db_schema_whitelist.json
- testData/actions/generation/generator/DbSchemaXmlGenerator/generateDbSchemaXmlFileForShortProperties/db_schema.xml
- tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaWhitelistGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/util/DbSchemaGeneratorDataProviderUtil.java
1. Column Attributes extracted to the enum type, added default values for them
2. Code refactoring after ColumnAttributes enum was added
3. Added possibility to create expected in the generators columns data from entity properties data
4. Added test coverage for the new feature
5. Code refactoring in the related files
6. Testing in the local env.
**Results:**
> Provide declarative schema features to entity manager

- resources/phpstorm.meta.php/di-autocomplete.php
This PR adds extended **.phpstorm.meta.php** for more convenient autocomplete.
1. Fixes magento/magento2-phpstorm-plugin#403
> Extended .phpstorm.meta.php for more convenient autocomplete

- resources/META-INF/plugin.xml
- resources/fileTemplates/code/Magento Entity Data Mapper.html.ft
- resources/fileTemplates/code/Magento Entity Data Mapper.php.ft
- src/com/magento/idea/magento2plugin/actions/generation/data/EntityDataMapperData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/EntityDataMapperFile.java
- src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
- testData/actions/generation/generator/EntityDataMapperClassGenerator/generateEntityDataMapperFile/UnicornDataMapper.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperClassGeneratorTest.java
1. added entity data mapper generator
2. added test for entity data mapper generation
3. stub for getting data mapper class FQN (used for getListQuery class) changed to the real data mapper class FQN
> Added entity data mapper generator and test for generation

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/NamespaceBuilder.java
This PR has fixes for a few bugs during entity manager generation. Also was refactored form dialog (UI Components methods renamed and grouped to be in the same place...added missed annotations)
**Found bugs:**
1. Create Admin UI Components checkbox is ignored
2. Controller/Adminhtml/Listing.php ends with a backslash in the namespace.
3. DTO model preference in the di.xml is wrong. Type attribute has Magento 2 Model FQN instead of DTO FQN.
**Here are the results:**
> Fixed few bugs with entity manager generation

- resources/magento2/validation.properties
- src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityControllerFileData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/AclResourceIdRule.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/MenuIdentifierRule.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/QueryGenerator.java
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
**I've fixed the entity manager dialog UX**:
1. Сorrected the size of the form.
2. Untitled tab renamed to Menu.
3. Added example to the following fields (Form Name, Grid Name, ACL ID, Identifier).
4. Added validation to the following fields (Form Name, Grid Name, ACL ID, Sort Order, Identifier).
> Fix mainline entity manager dialog form

- resources/META-INF/plugin.xml
- resources/fileTemplates/code/Magento Grid UI Component Column.xml.ft
- resources/fileTemplates/internal/Magento Entity Index Adminhtml Controller Class.php.ft
- resources/fileTemplates/internal/Magento Entity Index Adminhtml Controller Class.php.html
- resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.ft
- resources/fileTemplates/internal/Magento Grid Ui Component Action Column Class.php.html
- resources/fileTemplates/internal/Magento UI Component Grid XML.xml.ft
- src/com/magento/idea/magento2plugin/actions/generation/data/AdminListViewEntityActionData.java
- src/com/magento/idea/magento2plugin/actions/generation/data/GridActionColumnData.java
- src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentGridData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/AdminListViewEntityActionGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridXmlGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/GridActionColumnFile.java
- src/com/magento/idea/magento2plugin/magento/files/UiComponentGridXml.java
- src/com/magento/idea/magento2plugin/magento/files/actions/AdminListViewActionFile.java
- src/com/magento/idea/magento2plugin/magento/files/actions/SaveActionFile.java
- src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java
- testData/actions/generation/generator/AdminListViewEntityControllerGenerator/generateListViewControllerFile/Index.php
- testData/actions/generation/generator/GridActionColumnFileGenerator/generateGridActionColumnFile/BlockActions.php
- testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php
- testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/AdminListViewEntityControllerGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityActionGeneratorTest.java
1. added internal code template for columns
2. injected entity columns in the grid XML generation
3. fixed bug with the wrong path to adminhtml controllers
4. renamed Listing.php (listing controller) to Index.php
5. recreated listing controller generation (the old version haven't removed because used in the few places)
6. created grid actions columns file generation
7. added test case for list controller generation
8. added test case for grid actions column file generation
> Added entity columns to grid, recreated view controller, bug fixing, added actions column generation, test coverage

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento PHP Form Generic Button Block Class.php.ft
- resources/fileTemplates/internal/Magento PHP Form Generic Button Block Class.php.html
- resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
- src/com/magento/idea/magento2plugin/actions/generation/data/FormGenericButtonBlockData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/FormGenericButtonBlockFile.java
- src/com/magento/idea/magento2plugin/magento/packages/uiComponent/FormElementType.java
- testData/actions/generation/generator/FormGenericButtonBlockGenerator/generateFormGenericButtonBlockFile/GenericButton.php
- testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGeneratorTest.java
1. fixed save button class name
2. fixed form element value (provided enum and added its value to prev ui form generation)
3. fixed entity id field absent on the form
4. provided real entity id to the form
5. small entity manager form improving (margins for tabs)
6. developed generic button
7. developed test for generic button generation
8. adjusted data provider to provide the right data into the entity form
9. adjusted data provider test case
> Develop UI component form generation

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento New Entity Layout XML.xml.ft
- src/com/magento/idea/magento2plugin/actions/generation/data/NewEntityLayoutData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/NewEntityLayoutGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/NewEntityLayoutFile.java
- testData/actions/generation/generator/NewEntityLayoutGenerator/generateNewEntityLayoutFile/book_book_new.xml
- tests/com/magento/idea/magento2plugin/actions/generation/generator/NewEntityLayoutGeneratorTest.java
Added new entity layout generation and covered with a test case.
> Added new entity layout file generation, test for generation

- resources/fileTemplates/code/Magento Module UI Component Form Field Xml.xml.ft
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/magento/packages/uiComponent/FormElementType.java
I've fixed:
1. Changed the boolean field view on the form.
2. Converted labels for fields.
> Changed boolean field view on the form, converted labels for fields

- resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft
- resources/fileTemplates/internal/Magento UI Component Form XML.xml.ft
- testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml
- testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php
I've fixed the generator Data Provider Class and Ui component form.
 
> Fixed data provider to work with listing and form

- CHANGELOG.md
- src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
- src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
- testData/project/magento2/vendor/magento/module-catalog/test_event/TestObserver.php
- testData/reference/xml/ObserverReferenceRegistrar/observerInstanceDirectorySnakeCaseMustHaveReference/events.xml
- tests/com/magento/idea/magento2plugin/reference/xml/ObserverReferenceRegistrarTest.java
> Forwardport 3.1.2 >3.2.0

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Entity Edit Action Controller Class.php.ft
- resources/fileTemplates/internal/Magento Entity Edit Action Controller Class.php.html
- resources/fileTemplates/internal/Magento Entity Save Controller Class.php.ft
- resources/fileTemplates/internal/Magento Resource Model Class.php.ft
- resources/fileTemplates/internal/Magento Save Entity Command Model.php.ft
- src/com/magento/idea/magento2plugin/actions/generation/data/EditEntityActionData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/actions/EditEntityActionFile.java
- testData/actions/generation/generator/EditEntityActionGenerator/generateEditEntityActionFile/Edit.php
- testData/actions/generation/generator/ModuleResourceModelGenerator/generateFile/TestResourceModel.php
- testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php
- testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php
- testData/actions/generation/generator/SaveEntityCommandGenerator/generateSaveEntityCommandFile/SaveCommand.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGeneratorTest.java
1. Rewritten edit entity controller class
2. Added test case for edit entity controller class generation
3. finished saving entity flow
4. code refactoring
> Save entity flow development

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Entity Delete Controller Class.php.ft
- resources/fileTemplates/internal/Magento Entity Delete Controller Class.php.html
- src/com/magento/idea/magento2plugin/actions/generation/data/DeleteEntityControllerFileData.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityControllerFileGenerator.java
- src/com/magento/idea/magento2plugin/magento/files/actions/DeleteActionFile.java
- src/com/magento/idea/magento2plugin/magento/packages/code/ExceptionType.java
- testData/actions/generation/generator/DeleteEntityGenerator/generateDeleteEntityFile/Delete.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityGeneratorTest.java
I've implemented:
1. Generator for the "Delete Controller".
2. Added test for "Delete Controller'.
> Added Generator for Delete Controller

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
This PR aims to have a capitalized Entity Name while typing, in order to correctly use it for generating all the code.
N/A
> Entity manager capitalized entity name

- src/com/magento/idea/magento2plugin/actions/generation/data/CollectionData.java
- src/com/magento/idea/magento2plugin/actions/generation/data/ModelData.java
- src/com/magento/idea/magento2plugin/actions/generation/data/ResourceModelData.java
- src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/CollectionModelDtoConverter.java
- src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/ModelDtoConverter.java
- src/com/magento/idea/magento2plugin/actions/generation/data/converter/newentitydialog/ResourceModelDtoConverter.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassGeneratorUtil.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassTypesBuilder.java
- src/com/magento/idea/magento2plugin/magento/files/CollectionModelFile.java
- src/com/magento/idea/magento2plugin/magento/files/ModelFile.java
- src/com/magento/idea/magento2plugin/magento/files/ResourceModelFile.java
- testData/actions/generation/generator/ModuleCollectionGenerator/generateWithTheSameNamesForResourceModelAndModel/Collection.php
- testData/actions/generation/generator/ModuleModelGenerator/generateWithTheSameNameForResourceModel/Test.php
- tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGeneratorTest.java
- tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGeneratorTest.java
1. removed unnecessary namespace info from model DTO and all involved refactoring
2. removed unnecessary namespace info from resource model DTO and all involved refactoring
3. removed unnecessary namespace info from collection DTO and all involved refactoring
4. refactored models generation dialog class
5. refactored testing coverage for these models
6. added few test cases (alias added where it is required by new utility)
7. added utility that responsible for uses and properties management: PhpClassTypesBuilder
> Enhanced Model, Resource Model, Collection generation, fixed collection path bug, added PhpClassTypesBuilder, added new testcases testing

- src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
- src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
Fixes #531 
Fixed issue with the not set attribute value:
> Fixed error when plugin or observer name is not set

- gradle-tasks/staticChecks.gradle
Fixed CI building error:
Fix based on this [documentation](https://docs.gradle.org/current/userguide/pmd_plugin.html).
> Fixed error with builds in CI for the project

- build.gradle
Fixed missed Preferences menu in the sandbox ide:
> Changed intellij version to the latest version

- src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/PhpDirectoryRule.java
Fixed the bug of creating a subdirectory (for example “Block/Address/Renderer”) to create a new module file Magento Block, Magento Controller and Magento GraphQl Resolver.
> Fixed the bug of creating a subdirectory

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
Fixed namespace in the controller when creating a file with subdirectories
> Fixed namespace in controller

- src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java
Allows validate only visible fields on the dialog. 
Actual result. 
If we have dialog with required hidden fields and try to submit form, we will face issue:
https://user-images.githubusercontent.com/29776509/115829861-2745fa80-a418-11eb-9a07-694881c0ab78.mp4
It's make some inconvenience because if field are hidden we don't want to validate it.
This PR, add feature - ignore validation for hidden fields. Only visible fields will validate. 
Expected result:
https://user-images.githubusercontent.com/29776509/115830385-e13d6680-a418-11eb-98a6-a548faecd44a.mp4
> Added logic for validation only visible fields on the dialog

- resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft
- src/com/magento/idea/magento2plugin/actions/generation/dialog/util/eavdialog/AttributeUtil.java
- testData/actions/generation/generator/CategoryAttributePropertySetupPatchGenerator/generateFile/AddTestAttributeCategoryAttribute.php
- testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFile/AddTestAttribute.php
- testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php
- testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php
- testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php
- testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
This PR aims to:
- Fix the selected **SCOPE** attribute for generated EAV attributes
- Adding the returns for apply methods
N/A
> Fixing the EAV selected scope for the generated attributes

- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2uct/actions/ConfigureUctAction.java
- src/com/magento/idea/magento2uct/execution/DefaultExecutor.java
- src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java
- src/com/magento/idea/magento2uct/execution/ReindexUctCommand.java
- src/com/magento/idea/magento2uct/execution/process/DefaultAnalysisHandler.java
- src/com/magento/idea/magento2uct/execution/process/OutputWrapper.java
- src/com/magento/idea/magento2uct/execution/scanner/ModuleScanner.java
- src/com/magento/idea/magento2uct/execution/scanner/filter/ExcludeMagentoBundledFilter.java
- src/com/magento/idea/magento2uct/execution/scanner/filter/ModuleScannerFilter.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/CallingDeprecatedMethod.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/ExtendingDeprecatedClass.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/ImplementedDeprecatedInterface.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedClass.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedInterface.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/ImportingDeprecatedType.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/InheritedDeprecatedInterface.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedConstant.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/OverridingDeprecatedProperty.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedClass.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedConstant.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedInterface.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedProperty.java
- src/com/magento/idea/magento2uct/inspections/php/deprecation/UsingDeprecatedType.java
- src/com/magento/idea/magento2uct/settings/UctSettingsService.java
- src/com/magento/idea/magento2uct/ui/ConfigurationDialog.form
- src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
- src/com/magento/idea/magento2uct/ui/ReindexDialog.java
- src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
Added settings for the built-in UCT feature, moved actions to the Tools menu item, added is enabled and is min issue level satisfiable check for all inspections, added information message in the settings dialog window how to enable inspections in the real time, added filters to analysis output, added execution in the separate thread (non-blocking EDT mode), filtered modules for analysis to not include Magento bundled extensions.
> Enhanced analysis execution, added settings

- resources/inspectionDescriptions/CallingDeprecatedMethod.html
- resources/inspectionDescriptions/ExtendingDeprecatedClass.html
- resources/inspectionDescriptions/ImplementedDeprecatedInterface.html
- resources/inspectionDescriptions/ImportingDeprecatedClass.html
- resources/inspectionDescriptions/ImportingDeprecatedInterface.html
- resources/inspectionDescriptions/InheritedDeprecatedInterface.html
- resources/inspectionDescriptions/OverridingDeprecatedConstant.html
- resources/inspectionDescriptions/OverridingDeprecatedProperty.html
- resources/inspectionDescriptions/UsingDeprecatedClass.html
- resources/inspectionDescriptions/UsingDeprecatedConstant.html
- resources/inspectionDescriptions/UsingDeprecatedInterface.html
- resources/inspectionDescriptions/UsingDeprecatedProperty.html
- src/com/magento/idea/magento2uct/execution/configurations/UctRunConfiguration.java
- src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.form
- src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.java
- src/com/magento/idea/magento2uct/execution/output/ReportBuilder.java
- src/com/magento/idea/magento2uct/util/module/UctModuleLocatorUtil.java
The following enhancements have been made:
- Added context flag
- Removed default text placeholders from created inspection description files
- Changed ignoring radio button to checkbox
- Removed unnecessary empty item for minimum issue severity level combobox
> Additional changes to both the built-in UCT and UCT Run Configuration

- CHANGELOG.md
Modified CHANGELOG file before RELEASE v4.1.0.
> Modified CHANGELOG before release 4.1.0

- src/com/magento/idea/magento2uct/util/module/UctModuleLocatorUtil.java
- added alternative UCT module composer name
**Results:**
1. Fixes magento/magento2-phpstorm-plugin#782
> UCT-782: Added alternative UCT module name

- CHANGELOG.md
> Modified CHANGELOG before release 4.2.0

- CHANGELOG.md
Changelog update before release.
> Additional changes before 4.2.1 release

- src/com/magento/idea/magento2uct/util/php/MagentoTypeEscapeUtil.java
Fixed StringIndexOutOfBoundsException during UCT inspection via action execution.
1. Fixes magento/magento2-phpstorm-plugin#810
> 810: Fixed StringIndexOutOfBoundsException during UCT inspection via action execution

- src/com/magento/idea/magento2plugin/magento/packages/MessageQueueConnections.java
Fixed wrong RabbitMQ connection name.
**Before fixing:**
**After fixing:**
1. Fixes magento/magento2-phpstorm-plugin#837
> 837: Fixed wrong connection name

- src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java
Error correction in case entered fields is zero
1. Fixes magento/magento2-phpstorm-plugin#858
> 858: error correction in case entered fields is zero

- src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewViewModelAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
Enhanced error outputting for the new Magento 2 GraphQl resolver generation.
1. Fixes magento/magento2-phpstorm-plugin#871
> 871: enhanced new graphql resolver dialog UX

- src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
Enhanced error outputting for the new Magento 2 email template generation.
1. Fixes magento/magento2-phpstorm-plugin#873
> 873: enhanced new email template dialog UX

- resources/magento2/validation.properties
- src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
Enhanced error outputting for the new Magento 2 data model generation.
1. Fixes magento/magento2-phpstorm-plugin#875
> 875: enhanced new data model dialog UX

- resources/magento2/validation.properties
- src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java
- src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
Enhanced error outputting for the new Magento 2 message queue generation.
1. Fixes magento/magento2-phpstorm-plugin#876
> 876: enhanced new message queue dialog UX

- CHANGELOG.md
- build.gradle
- src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
Picking last changes from the 4.2.1-develop.
> Update 4 2 2 develop from 4 2 1 develop

- README.md
> Removed merge chance

- CHANGELOG.md
Updated changelog for release 4.2.2.
> Updated changelog for release 4.2.2

- src/com/magento/idea/magento2plugin/lang/injection/UiComponentSyntaxInjector.java
Added integration enabled check for uiComponent
1. Fixes magento/magento2-phpstorm-plugin#941
> 941: added integration enabled check for uiComponent

- src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
Fixed style check to proceed with the ALPHA release 4.2.3.
> Fixed style check

- CHANGELOG.md
- build.gradle
> Added simple-json library to the project distribution

- src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
I added missed titles to some forms.
Magento 2 Email Template form:
and Magento 2 Models form: 
1. Fixes magento/magento2-phpstorm-plugin#955
> 955 add missing title to form

- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/actions/context/xml/NewWebapiXmlAction.java
968: Added a new context dependent Action for the webapi.xml file generation
1. Fixes magento/magento2-phpstorm-plugin#968
> 968: Added a new context dependent Action for the webapi.xml file generation

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento ACL XML.xml.ft
- src/com/magento/idea/magento2plugin/actions/context/xml/NewAclXmlAction.java
965: Added a new context dependent Action for the acl.xml file generation
1. Fixes magento/magento2-phpstorm-plugin#965
> 965: Added a new context dependent Action for the acl.xml file generation

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Config XML.xml.ft
- resources/fileTemplates/internal/Magento Config XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewConfigXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleConfigXmlFile.java
Add a new context dependent Action for the config.xml file generation
1. Fixes magento/magento2-phpstorm-plugin#975
> 975: Added a new context dependent Action for the config.xml file generation

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Mview XML.xml.ft
- resources/fileTemplates/internal/Magento Mview XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewMviewXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleMviewXmlFile.java
Added mview.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#985
> 985: Added mview.xml file in context generation.

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento View XML.xml.ft
- resources/fileTemplates/internal/Magento View XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewViewXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleViewXmlFile.java
Added view.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#989
> 989: Added view.xml file in context generation.

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Fieldset XML.xml.ft
- resources/fileTemplates/internal/Magento Fieldset XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewFieldsetXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleFieldsetXmlFile.java
Added fieldset.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#991
> 991: Added fieldset.xml file in context generation.

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Sections XML.xml.ft
- resources/fileTemplates/internal/Magento Sections XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewSectionsXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModuleSectionsXmlFile.java
Added sections.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#992
> 992: Added sections.xml file in context generation.

- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/actions/context/xml/NewEmailTemplatesXmlAction.java
Added email_templates.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#993
> 993: Added email_templates.xml file in context generation.

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Magento Page Types XML.xml.ft
- resources/fileTemplates/internal/Magento Page Types XML.xml.html
- src/com/magento/idea/magento2plugin/actions/context/xml/NewPageTypesXmlAction.java
- src/com/magento/idea/magento2plugin/magento/files/ModulePageTypesXmlFile.java
Added page_types.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#995
> 995: Added page_types.xml file in context generation.

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
1. Fixes magento/magento2-phpstorm-plugin#959
> 959: Moving Example to the placeholder

- src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
1. Fixes magento/magento2-phpstorm-plugin#1000
> 1000: Fixed ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5(GetModuleNameByDirectoryUtil.java:47)

- src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Fixed bug with the wrong file separator on the Windows OS.
1. Fixes magento/magento2-phpstorm-plugin#1058
> 1058: Fixed bug with the file separator on windows

- build.gradle
Added raw plugin verifier configuration.
1. Fixes magento/magento2-phpstorm-plugin#1050
> 1050: added raw plugin verifier configuration

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewLayoutTemplateDialog.java
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
I changed validation for new layout name to fix the bug.
1. Fixes magento/magento2-phpstorm-plugin#1094
> 1094 fix a new layout action error

- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
Fix bug index out of bounds in OverrideClassByAPreferenceDialog class
1. Fixes magento/magento2-phpstorm-plugin#1122
> 1122 fix bug index out of bounds in OverrideClassByAPreferenceDialog class

- src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
Added check for moduleName variable to prevent IllegalArgumentException.
1. Fixes magento/magento2-phpstorm-plugin#1131
> 1131 fix bug null data in ModuleIndex class

- resources/fileTemplates/includes/MD File Description.md.ft
- resources/fileTemplates/internal/Magento Module Readme File MD.md.ft
- testData/actions/generation/generator/ModuleReadmeMdGenerator/generateModuleReadmeMdFile/README.md
This pull request (PR) provides, changing default README.md text.
1. Fixes magento/magento2-phpstorm-plugin#1174
> 1174: Changing default README.md text

- src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
Fixed ClassCastException.
1. Fixes magento/magento2-phpstorm-plugin#1180
> 1180: Fixed ClassCastException

- src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Fix NullPointerException at ObserverDeclarationInspection Class
1. Fixes magento/magento2-phpstorm-plugin#1143
> 1143 fix NullPointerException at ObserverDeclarationInspection Class

- build.gradle
- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
Reverts magento/magento2-phpstorm-plugin#1182
> Revert "Fixed new intellij version compatibility issues"

- build.gradle
- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
> Reverting raw code from the 5.0.0-develop

- CHANGELOG.md
- resources/magento2/validation.properties
- src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java
- src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
- src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
- src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java
- src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
- src/com/magento/idea/magento2plugin/magento/packages/MagentoComponentManager.java
- src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java
- src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
- src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
- src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Mainline branch actualisation.
> Update 5.0.0 develop from 4.4.0 develop

- resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft
- testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
Fixed customer EAV attribute generation for Magento 2.4.4 (PHP8.1).
1. Fixes magento/magento2-phpstorm-plugin#1196
> 1196 fix customer eav attr generation for m 2.4.4

- resources/META-INF/plugin.xml
- resources/META-INF/withJsGraphQl.xml
- resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft
- testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
Merge last changes from 4.4.0-develop into the 5.0.0-develop.
> Merge 4.4.0 develop into 5.0.0 develop

- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/actions/generation/OverrideFileAction.java
- src/com/magento/idea/magento2plugin/actions/generation/OverrideLayoutInThemeAction.java
- src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInModuleAction.java
- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInModuleDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInModuleDialog.java
- src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInModuleGenerator.java
Added to the action menu item to override a template in a module.
> 1171: Override template in a module

- resources/META-INF/plugin.xml
- resources/inspectionDescriptions/ModuleScopeInspection.html
- resources/magento2/inspection.properties
- src/com/magento/idea/magento2plugin/inspections/xml/ModuleScopeInspection.java
- testData/inspections/xml/ModuleScopeInspection/correctArea/app/code/Test/TestModule/etc/adminhtml/di.xml
- testData/inspections/xml/ModuleScopeInspection/correctArea/app/code/Test/TestModule/registration.php
- testData/inspections/xml/ModuleScopeInspection/incorrectArea/app/code/Test/TestModule/etc/adminhtmltypo/di.xml
- testData/inspections/xml/ModuleScopeInspection/incorrectArea/app/code/Test/TestModule/registration.php
- tests/com/magento/idea/magento2plugin/inspections/xml/ModuleScopeInspectionTest.java
See https://github.com/magento/magento2-phpstorm-plugin/pull/1243
> Config Scope directory inspection

- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form
- src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form
Description (*)
Added default group to product and category EAV generators to enhance usability:
> EAV attributes code generators: Added default values of group property

- src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
> 1220: fixed PluginIndex

- CHANGELOG.md
> adjusted CHANGELOG.md

- .github/workflows/gradlepublish.yml
> Updated gradlepublish.yml

- .github/workflows/gradle.yml
- .github/workflows/gradlepublish.yml
- .github/workflows/gradlepublishalpha.yml
- build.gradle
- gradle-tasks/staticChecks.gradle
> Updated actions

- .github/workflows/gradle.yml
- .github/workflows/gradlepublish.yml
- .github/workflows/gradlepublishalpha.yml
- README.md
- build.gradle
- resources/META-INF/plugin.xml
- src/com/magento/idea/magento2plugin/actions/groups/NewEavAttributeGroup.java
- src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java
- src/com/magento/idea/magento2plugin/init/ConfigurationManager.java
additional compatibility fixes
> 5.1.0 - additional compatibility fixes

- resources/fileTemplates/internal/Magento CLI Command Class.php.html
> Typo `Magneto` -> `Magento`

- CHANGELOG.md
- src/com/magento/idea/magento2plugin/util/RegExUtil.java
1. Fixes magento/magento2-phpstorm-plugin#1517
> 1517: Custom theme couldn't be detected - fix
