magento/magento2-phpstorm-plugin

src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
- Go to any xml/javascript file containing file path declaration and try to navigate, for example:
`vendor/magento/module-catalog/view/adminhtml/requirejs-config.js`
- Nothing happens
- Navigation works properly, you can navigate to appropriate element from xml/javascript file
=> Reference for file path declared in XMl/JavaScript are broken

src/com/magento/idea/magento2plugin/project/Settings.java
This allows the latest intellij community SDK to be used for building
`id` in Storage interface has been removed in https://github.com/JetBrains/intellij-community/commit/66bbb298b1c9a3afea8000c0a5588cedabd3d649#diff-ab396582d6774e7ffb0632b9fafe6e8aL26
`StoragePathMacros.PROJECT_FILE` and `StoragePathMacros.PROJECT_CONFIG_DIR` has been removed in https://github.com/JetBrains/intellij-community/commit/d1f3e40c4fa321aab76560eb1d99e7ad0617f214#diff-082ba6a4cca1c83eb7e5490c6b8d2bc0L49
=> Update Storage implementation in Settings.java to be compatible with latest annotation interface

META-INF/plugin.xml, src/com/magento/idea/magento2plugin/graphql/linemarker/GraphQlResolverClassLineMarkerProvider.java, src/com/magento/idea/magento2plugin/indexes/IndexManager.java, src/com/magento/idea/magento2plugin/php/linemarker/GraphQlResolverUsageLineMarkerProvider.java, src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java, src/com/magento/idea/magento2plugin/util/magento/graphql/GraphQlUtil.java
Added line markers for GraphQL.
Class -> Schema:
Schema -> Class:
=> Line Markers for GraphQl navigation

resources/fileTemplates/code/Magento Plugin After Method.html, resources/fileTemplates/code/Magento Plugin After Method.php.html, resources/fileTemplates/code/Magento Plugin Around Method.html, resources/fileTemplates/code/Magento Plugin Around Method.php.html, resources/fileTemplates/code/Magento Plugin Before Method.html, resources/fileTemplates/code/Magento Plugin Before Method.php.html
Fixed https://github.com/magento/magento2-phpstorm-plugin/issues/44
This PR will add the plugin description in the plugin code templates
**After Plugin**
**Before Plugin**
**Around Plugin**
=> #44 :- Templates. Fill information about Plugin Templates

resources/META-INF/plugin.xml, resources/META-INF/withJsGraphQl.xml, src/com/magento/idea/magento2plugin/php/linemarker/GraphQlResolverUsageLineMarkerProvider.java, src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
This PR introduces a change that makes the JSGraphQl module an optional dependency for the current plugin. With this change In case if the JSGraphQl is disabled or not installed the Magento module will still work but without GraphQL line markers and other GraphQl-related functionality.
Please note that the dependency should still exist in the `build.gradle` since it's required for the module compilation with all possible dependencies (including optional). 
#43 : Line Marker. Remove GraphQlJS hard dependency 
- Compile/build the module with the new configuration
- Open IDE with the module installed 
- Disable JSGraphQl module
- The Magento module should still be enabled and working
=> JSGraphql configured as an optional dependency

resources/fileTemplates/internal/Magento Module Composer.json.ft, resources/fileTemplates/internal/Magento Module Composer.json.html
Added description for the Module's composer.json file and adjusted the template code style.
=> Module's composer.json template adjustments

CHANGELOG.md, resources/META-INF/plugin.xml, resources/fileTemplates/code/Magento Module DI Xml Preference.xml.ft, resources/fileTemplates/code/Magento Module DI Xml Preference.xml.html, resources/fileTemplates/internal/Magento Php Preference Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/OverrideClassByAPreferenceAction.java, src/com/magento/idea/magento2plugin/actions/generation/data/PreferenceDiXmFileData.java, src/com/magento/idea/magento2plugin/actions/generation/data/PreferenceFileData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMagentoModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PluginDiXmlGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceDiXmlGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/FindOrCreateDiXml.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetCodeTemplate.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/XmlFilePositionUtil.java, src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java, src/com/magento/idea/magento2plugin/magento/files/PhpPreference.java
Added new action for overriding a class by preference
=> Added override class by a preference action

resources/fileTemplates/internal/Magento Module Registration Php.php.html
This PR adds the description for the `Magento Module Registration Php.php.ft` template.
=> Added the module's registration.php template description

src/com/magento/idea/magento2plugin/actions/generation/util/MagentoVersion.java, src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java, src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java, src/com/magento/idea/magento2plugin/magento/packages/Package.java, src/com/magento/idea/magento2plugin/project/SettingsForm.form, src/com/magento/idea/magento2plugin/project/SettingsForm.java, tests/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspectionTest.java
This PR adds a new util class that retrieves the Project's Magento version from the `composer.json` file in the project's root.
1. magento/magento2-phpstorm-plugin#51: Magento Versioning. Create a Util class for defining a Magento version
(uses deprecated methods)
```java
DataContext dataContext = DataManager.getInstance().getDataContext();
this.project = (Project) dataContext.getData(DataConstants.PROJECT);
```
ℹ️ Instead of using a hard dependency on https://plugins.jetbrains.com/plugin/7631-php-composer-json-support as mentioned in the issue comments, I've used the existing class `com.magento.idea.magento2plugin.php.module.ComposerPackageModelImpl` in the project to get information from a `composer.json` file.
=> Show the current project's Magento version in settings window

src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java, src/com/magento/idea/magento2plugin/magento/files/ModuleSystemXml.java, src/com/magento/idea/magento2plugin/magento/files/SystemXml.java
This PR will add PHP class completion for the `frontend_model` XML tag
1. magento/magento2-phpstorm-plugin#90: Completion. Add PHP classes completion to the frontend_model attribute and tag
=> #90 :- Completion. Add PHP classes completion to the frontend_model attribute and tag

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
The PR fixes an issue reported in #112 and introduced in #92 
1. magento/magento2-phpstorm-plugin#112 Module Block namespace is wrong when creating new module Block via form dialog.
Please see the original issue description.
N/A
=> [bugfix] Code generation: module block namespace is corrupt

src/com/magento/idea/magento2plugin/generation/NewModuleForm.java
Added missed listeners for fields with validation to make the form validation to be refreshed immediately.
=> Fixed listeners on new module form for PHPStorm

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java, src/com/magento/idea/magento2plugin/magento/files/ComposerJson.java
- Added option to select no dependencies;
- Corrected the dependency module name in the composer.json file
```json
{
"name": "vendor/module",
"version": "1.0.0",
"description": "N/A",
"type": "magento2-module",
"require": {
"magento/framework": "*",
"magento/module-catalog-rule-configurable": "100.3.*",
"module/plugin-testing-module": "1.0.*",
"module/second-plugin-testing-module": "1.0.*"
},
"license": [
""
],
"autoload": {
"files": [
"registration.php"
],
"psr-4": {
"Vendor\\Module\\": ""
}
}
}
```
1. magento/magento2-phpstorm-plugin#151: Wrong dependency declared in composer JSON when creating a module
N/A
=> Wrong dependency declared in composer JSON when creating a module

src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java
This PR fixes the performance issue with line markers.
The issue has been caused by Plugin Line markers.
1. magento/magento2-phpstorm-plugin#31: Line markers. Fix performance warnings
Visit any target class. The console should not have the following errors:
=> Fixed performance issues on Plugin Line Market

src/com/magento/idea/magento2plugin/indexes/IndexManager.java
Fixed null pointer exception on the indexer.
When the module is enabled, module indexers need some time to be registered. I've added try-catch to prevent error when click happened before indexers are registered.
1. magento/magento2-phpstorm-plugin#158: Null pointer exception on manual reindex
=> Fixed null pointer exception

src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
This PR fixes null pointer exception when editing events.xml file
1. magento/magento2-phpstorm-plugin#168: Null Pointer on Observer Declaration inspection
=> Fixed null pointer exception on ObserverDeclarationInspection

src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java, src/com/magento/idea/magento2plugin/magento/files/Plugin.java
This PR fixes the issue with \Closure in around plugin and Plugin inspection.
1. magento/magento2-phpstorm-plugin#160: Plugin inspection. Closure recognized as a wrong parameter for around plugin
=> Fixed error on around plugin

src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java, src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java, testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml, testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInActionGroupMustProvideCompletion/TestActionGroup.xml, testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml, testData/completion/xml/MftfSelectorCompletionRegistrar/selectorInTestMustProvideCompletion/TestMftfTest.xml, testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustBeEmpty/TestActionGroup.xml, testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInActionGroupMustHaveReference/TestActionGroup.xml, testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustBeEmpty/TestMftfTest.xml, testData/reference/xml/MftfSelectorReferenceRegistrar/selectorInTestMustHaveReference/TestMftfTest.xml, tests/com/magento/idea/magento2plugin/completion/xml/MftfSelectorCompletionRegistrarTest.java, tests/com/magento/idea/magento2plugin/reference/xml/MftfSelectorReferenceRegistrarTest.java
This PR fixes sections autocomplete and reference for XML tag "selector"
1. magento/magento2-phpstorm-plugin#106: MFTF: Section name and elements autocomplete and reference
=> Fixed MFTF selector reference contributor and completion, added tes coverage

src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
1. magento/magento2-phpstorm-plugin#182: NullPointerException in PhpStorm 2020.1
=> Fixed null pointer exception in the PluginDeclarationInspection

src/com/magento/idea/magento2plugin/actions/generation/generator/code/PluginMethodsGenerator.java
This PR fixed issue with wrong namespaces.
This PR fixed two issues with namespace:
1. A wrong namespace for the first method parameter in the plugin if the name of the plugin and class are the same. I added the full path for first method parameter
1. I fixed the wrong namespace for the second method parameter in the plugin.
1. magento/magento2-phpstorm-plugin#156: Wrong namespace for method parameters in plugin
- **for the first issue:**
1. open file Magento\Catalog\Api\ProductRepositoryInterface
2. create a new plugin. >> Set plugin class name is like the same as the name of the file (ProductRepositoryInterface)
3. open new plugin file >> The first parameter must be with the full namespace.
- **for the second issue:**
1. open file Magento\Catalog\Api\ProductRepositoryInterface
2. create …
=> #156: fix issue with wrong namespaces

resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/inspections/php/fix/PhpImplementResolverClassQuickFix.java, src/com/magento/idea/magento2plugin/magento/files/GraphQlResolver.java
This PR will add following interface to implement resolver
1. `Magento\Framework\GraphQl\Query\ResolverInterface`
2. `Magento\Framework\GraphQl\Query\Resolver\BatchResolverInterface`
3. `Magento\Framework\GraphQl\Query\Resolver\BatchServiceContractResolverInterface`
1. magento/magento2-phpstorm-plugin#169: Quick fix for Resolver inspection adds implement directive to the next line
I'm not able to reproduce the issue with the interface applied to the next line. I will check again this issue
=> #169 :- Quick fix for Resolver inspection adds implement directive to the next line

src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java, src/com/magento/idea/magento2plugin/generation/php/NewModuleForm.java, src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java, src/com/magento/idea/magento2plugin/magento/packages/File.java, src/com/magento/idea/magento2plugin/util/magento/FileBasedIndexUtil.java, src/com/magento/idea/magento2plugin/util/magento/MagentoVersion.java, tests/com/magento/idea/magento2plugin/BaseProjectTestCase.java, tests/com/magento/idea/magento2plugin/completion/xml/CompletionXmlFixtureTestCase.java, tests/com/magento/idea/magento2plugin/inspections/php/InspectionPhpFixtureTestCase.java, tests/com/magento/idea/magento2plugin/inspections/xml/InspectionXmlFixtureTestCase.java, tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java, tests/com/magento/idea/magento2plugin/linemarker/php/LinemarkerPhpFixtureTestCase.java, tests/com/magento/idea/magento2plugin/reference/php/ReferencePhpFixtureTestCase.java, tests/com/magento/idea/magento2plugin/reference/xml/ReferenceXmlFixtureTestCase.java
Replaced `java.io.File` with the custom implementation to fix compatibility with the Windows os.
Some features were broken before changes provided in the PR, for example creating a view model popup had been never shown.
=> Implemented custom file separator, utilize java.io.File breaks Windows

resources/magento2/common.properties, resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAPluginDialogValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/CreateAnObserverDialogValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewBlockValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewGraphQlResolverValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewModuleDialogValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/NewViewModelValidator.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/OverrideClassByAPreferenceDialogValidator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleBlockClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleViewModelClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ObserverClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PreferenceClassGenerator.java, src/com/magento/idea/magento2plugin/bundles/CommonBundle.java, src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java, src/com/magento/idea/magento2plugin/inspections/xml/CacheableFalseInDefaultLayoutInspection.java, src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
This PR extracts the static text to separate bundles, that will cleanup the hardcoded phrases.
1. magento/magento2-phpstorm-plugin#149: Extracting the static text to separated message bundles.
We aren't able to use message bundling into static methods.
=> Managing the static phrases to use the bundle messages

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
This PR fixes the positioning for all the dialogs on the center screen. Currently, all the Dialogs are wrong positioned, because of the wrong calculated position based on width/height of the Dialog.
N/A
1. Open any dialog (Create a New Module/New Plugin/Observer/etc)
2. The Dialog should be perfectly positioned on the center of the screen
And again we have to find a workaround to work with `static` methods.
=> Fixing the positioning of all Dialogs on the center screen

src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java
This PR fixes issue CreateAPluginAction accessible from the wrong context. 
*For example*, it was accessible from right-clicking on the js file ⛔:
*Now* it is accessible only for right-clicking on class public method ✅:
=> Fix for CreateAPluginAction accessible from the wrong context

gradle-tasks/pmd/ruleset.xml, testData/completion/xml/LayoutContainerCompletionRegistrar/referenceContainerMustHaveCompletion/default.xml, testData/project/magento2/vendor/magento/module-catalog/view/frontend/layout/test_index_index.xml, testData/reference/xml/LayoutContainerReferenceRegistrar/referenceContainerMustHaveReference/default.xml, tests/com/magento/idea/magento2plugin/completion/xml/LayoutContainerCompletionRegistrarTest.java, tests/com/magento/idea/magento2plugin/reference/xml/LayoutContainerReferenceRegistrarTest.java
This PR covers `referenceContainer` in layout XML completion and reference by tests.
Also I've disabled redundant checks:
`JUnit4TestShouldUseTestAnnotation` -  disabled because we are using JUnit3;
`AtLeastOneConstructor` - have to be suppressed in tests all the time, and I see no reason for such check. If a constructor is needed it will be declared either way, otherwise, the code won't work :)
=> Covered referenceContainer related functionality by tests

src/com/magento/idea/magento2plugin/util/RegExUtil.java
The latest releases of Magento 2 can have a version like `2.3.5-p1` This PR provides an update for the version validation RegExp.
Steps to reproduce: Set the `Magento version` to 2.3.5-p1 and try to activate the Apply button at the Magento 2 PHPStorm plugin settings. For example, click on enable/disable plugin checkbox.
Result will be 
N/A
=> FIX: adjust Magento version validation RegExp

src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
This PR improves the inspection for plugin's arguments, which gives the possibility to use variadic (...) arguments. It also improves the inspection by additionally checking the argument's doctype if none is declared.
```php
/**
* @param Model $subject
* @param callable $proceed
* @param int $param
*/
public function aroundExecute(Model $subject, callable $proceed, $param)
{
return $proceed();
}
```
1. magento/magento2-phpstorm-plugin#271: Plugin declaration inspection is not supporting variadic arguments.
=> Improving the plugin's arguments inspection

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/util/HighlightDialogFieldOnErrorUtil.java
**Description (*)**
This PR adds error highlighting to validation through annotations. Related issue: #306 
**Here is the result of errors highlighting:**
=> 306: Added highlighting in error style to JComponent elements

src/com/magento/idea/magento2plugin/project/SettingsForm.form
Refactored labels in the settings form for consistency with other settings forms and grammar.
=> Refactored settings form

resources/fileTemplates/internal/Magento Module UI Component Form Xml.xml.ft, src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentFormFieldsetData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/ui/component/FormFieldsetsValidator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/code/XmlDeclarationsGenerator.java, testData/actions/generation/generator/UiComponentFormGenerator/generateFormXmlFile/my_form.xml, tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormGeneratorTest.java
Adjusted UI form generation, fixed data provider, and fieldset declarations.
FIxed tests.
Beautified headers in form.
=> Adjusted UI form XML to be valid and accessible via the admin

src/com/magento/idea/magento2plugin/project/SettingsForm.java
This PR fixes the inconsistency while enabling/disabling this plugin in the settings. When a plugin is disabled, all its related fields must be disabled. Having it enabled at all times confuses the user, from a UX point of view. This PR hence disables and enables all the related fields dynamically on settings page open event, and on change event of the plugin status checkbox.
=> Added form field status to reflect plugin status

src/com/magento/idea/magento2plugin/project/SettingsForm.form, src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java
This PR fixes the a bug present while saving the plugin settings. 
In, the `com.magento.idea.magento2plugin.project.validator.SettingsFormValidator#validate` method, `SettingsForm.getSettings()` method is used to check if plugin is enabled. While this works, this returns only the saved values and not the current values of the form. `SettingsForm.isBeingUsed()` on the other hand, returns the current value of the checkbox for plugin enablement. Please go through the below steps to better understand the flow. 
**Steps to reproduce bug**
1.  Open IntelliJ with plugin installed and navigate to the plugin settings
2.  Check the plugin enable checkbox and enter valid values for Magento path.
3.  Save. (this is successful)
4.  Uncheck the plugin enable checkbox and remove the …
=> Fixed validator when plugin is disabled

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java
This PR fixes couple of issues related to Ui form generation:
- Fixed the modal size ✅ 
- Fixed the Sort Order value for fieldset row ✅ 
=> Fixing the dialog size. Fixing adding new form fieldset

src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
New module action is broken with error:
```
ava.lang.NumberFormatException: For input string: "any"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at com.magento.idea.magento2plugin.util.magento.MagentoVersionUtil.compare(MagentoVersionUtil.java:90)
at com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDial
```
It happens if the Magento version is set to `any` in configs.
This PR fixes the issue.
=> Fixed new module action

src/com/magento/idea/magento2plugin/project/startup/CheckIfMagentoPathIsValidActivity.java
Fixed issue with constant disabling on startup when Magento not in the root.
1. magento/magento2-phpstorm-plugin#342: Plugin automatically disables after PhpStorm restart
=> Fixed disabling plugin on a startup when Magento not in the root

resources/fileTemplates/internal/Magento Php Preference Class.php.html, resources/fileTemplates/internal/Magento Routes Xml.xml.html
This PR will add the code template description for the routes.xml
1. Fixes magento/magento2-phpstorm-plugin#291
=> #291 :- Add routes.xml code template description

src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java
Added BoxNotEmptyRule to validators where original verbose validations were removed
1. Fixes magento/magento2-phpstorm-plugin#322: Implement module name validation in 'Create a plugin' and 'New module' dialog
**Questions**
How do we handle the issue raised at https://github.com/magento/magento2-phpstorm-plugin/pull/318#discussion_r508719248?
=> Added BoxNotEmptyRule to validators

src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java
Backport for https://github.com/magento/magento2-phpstorm-plugin/pull/328
=> Added linemarker for interface plugin target (backport)

src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
Fixed Viewmodel argument name validation as per reported issue
1. Fixes magento/magento2-phpstorm-plugin#369: Change the validation of the Argument Name field in the ViewModel dialog window
=> Fixed InjectAViewModel validation

src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
This commit adjusts the editable theme filter to only exclued composer
themes in `vendor/magento`. All other themes installed via composer will
appear in the theme list when using the "Override this template in a
project theme" action.
1. Fixes magento/magento2-phpstorm-plugin#64
@VitaliyBoyko This resolves the feedback resulting in the reopening of #64, though I'm not sure it is a desirable feature. This change will add non-magento themes in `vendor` to the list of editable themes when using the override in theme action, but this already works for themes installed via composer locally if the local package exists within the project root directory. For example if you are installing a theme via `path` using …
=> Allow theme override of non-magento composer themes

src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
**Backport #386**
This commit adjusts the editable theme filter to only exclued composer
themes in `vendor/magento`. All other themes installed via composer will
appear in the theme list when using the "Override this template in a
project theme" action.
1. Fixes magento/magento2-phpstorm-plugin#64
=> Backport #386 Allow theme override of non-magento composer themes

src/com/magento/idea/magento2plugin/reference/provider/PluginReferenceProvider.java, src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java, testData/reference/xml/DisabledPluginReferenceRegistrar/disabledPluginNameMustHaveReference/di.xml, tests/com/magento/idea/magento2plugin/reference/xml/DisabledPluginReferenceRegistrarTest.java
Added reference for disabled plugins through the plugin name.
1. Fixes magento/magento2-phpstorm-plugin#146: Reference navigation. Reference: disabled plugin declaration -> plugin declaration
=> Added XML reference for disabled plugins

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/completion/php/PhpCompletionContributor.java, src/com/magento/idea/magento2plugin/reference/php/PhpReferenceContributor.java, src/com/magento/idea/magento2plugin/util/php/PhpPatternsHelper.java, testData/completion/php/ConfigPhpModuleCompletionRegistrar/moduleNameMustHaveCompletion/config.php, testData/completion/php/ConfigPhpModuleCompletionRegistrar/moduleNameMustNotHaveCompletion/config.php, testData/reference/php/ConfigPhpModuleReferenceRegistrar/moduleNameMustHaveReference/config.php, testData/reference/php/ConfigPhpModuleReferenceRegistrar/moduleNameMustNotHaveReference/config.php, tests/com/magento/idea/magento2plugin/completion/BaseCompletionTestCase.java, tests/com/magento/idea/magento2plugin/completion/php/CompletionPhpFixtureTestCase.java, tests/com/magento/idea/magento2plugin/completion/php/ConfigPhpModuleCompletionRegistrarTest.java, tests/com/magento/idea/magento2plugin/completion/xml/CompletionXmlFixtureTestCase.java, tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java, tests/com/magento/idea/magento2plugin/reference/php/ConfigPhpModuleReferenceRegistrarTest.java
- Added completion and reference to modules names under the `modules` array in `config.php`
- Added postive/negatives tests for the above
- Added new test assertion `assertHasNoReferenceToDirectory`
- Moved common logic from `completion/xml/CompletionXmlFixtureTestCase.java` to `completion/BaseCompletionTestCase.java` to make it extensible and cleaned up code wherever possible
- Fixes magento/magento2-phpstorm-plugin#321: Add module names completion and reference in config.php
**Questions**
- The same `ElementPattern` does not work for both completion and reference. Reference seems to work only when using `psiElement(StringLiteralExpression.class)` and completion seems to work only when using the child of the previously mentioned element, …
=> Added completion and reference for module names in config.php with tests

resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java, testData/inspections/xml/PluginDeclarationInspection/disabledNonExistingPlugin/di.xml, tests/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspectionTest.java
This PR adds
- inspection warning for disabling of a plugin which doesn't exist in `di.xml`
- test coverage
- magento/magento2-phpstorm-plugin#147: Inspection. Disabled plugin declaration
=> Inspection warning for disabling of an invalid plugin

resources/fileTemplates/internal/Magento Php Form Button Block Class.php.ft, resources/fileTemplates/internal/Magento Php Form Button Block Class.php.html
Added template content for UI Component Form button class
- magento/magento2-phpstorm-plugin#287: Add PHP form button block class code template description
=> Added file template content for Form button class

src/com/magento/idea/magento2plugin/reference/provider/PhpJobMethodReferenceProvider.java, testData/reference/xml/CrontabReferenceRegistrar/crontabMethodMustNotHaveReference/crontab.xml, tests/com/magento/idea/magento2plugin/reference/BaseReferenceTestCase.java, tests/com/magento/idea/magento2plugin/reference/xml/CrontabReferenceRegistrarTest.java, tests/com/magento/idea/magento2plugin/reference/xml/WebApiMethodReferenceRegistrarTest.java
Added test coverage for `PhpJobMethodReferenceProvider`
=> Covered PhpJobMethodReferenceProvider with tests

resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/inspections/graphqls/SchemaResolverInspection.java, src/com/magento/idea/magento2plugin/inspections/graphqls/fix/CreateResolverClassQuickFix.java
Added QuickFix for mising GraphQL resolver in schema.graphqls file.
1. Fixes magento/magento2-phpstorm-plugin#217: Add a QuickFix for GraphQL schema inspection
=> Added QuickFix for missing GraphQL resolver

src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
To reproduce the issue remove the original method name part from the plugin method name e.g
beforeExecute -> before
-->
1. Fixes magento/magento2-phpstorm-plugin#286
=> #286 Fixed StringIndexOutOfBoundsException on PluginInspection

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/IdentifierWithColonRule.java, src/com/magento/idea/magento2plugin/util/RegExUtil.java
This PR fixes the plugin validator as described in the issue
1. Fixes magento/magento2-phpstorm-plugin#422: Change the validation of the Plugin Name field in the New Plugin dialog window
=> Fixed plugin name validator

src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
This PR fixes the null pointer exception occurring when injecting a view model in a layout file from `app/design` directory.
1. Fixes magento/magento2-phpstorm-plugin#433: java.lang.NullPointerException when inject view model in theme layout file
- Currently, I check if the path of the layout file is a theme, and then extract the module name from the path (project_root/app/design/frontend/Vendor/theme/**_Magento_Catalog_**/layout). But the problem with this is that this specific module is usually a vendor module and the view model file is created in the vendor directory. Either we don't create a view model file if view model is being injected in a vendor module, and just stick to creating the layout entry for the same. Or, we ask …
=> Fixed NPTR exception in theme directory view model action

resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java, testData/inspections/xml/ObserverDeclarationInspection/disablingNonExistingObserver/events.xml, tests/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspectionTest.java
This PR adds
- inspection warning for disabling of an observer which doesn't exist
- test coverage
1. Fixes magento/magento2-phpstorm-plugin#424: Inspection warning when disabling a nonexistent observer in events.xml
=> Added inspection warning for disabled observer

CHANGELOG.md, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java
Fixed generation of models with same model/resource model name.
1. Fixes magento/magento2-phpstorm-plugin#437: The added model and collection classes contain duplicate names of the imported classes
=> Fixed model generation with same names

src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java
The following PR allows overriding the templates that are located in `base` area. This way, the developer can override a base template in any existing frontend/backend themes.
1. Fixes magento/magento2-phpstorm-plugin#441
=> [Code Generation] Fixing overriding a template from the base area

resources/fileTemplates/internal/Magento Data Model Interface.php.ft, resources/fileTemplates/internal/Magento Data Model.php.ft, src/com/magento/idea/magento2plugin/actions/generation/data/DataModelData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java, testData/actions/generation/generator/DataModelGenerator/generateDataModel/Sample.php, testData/actions/generation/generator/DataModelGenerator/generateDataModelWithoutInterface/Sample.php, testData/actions/generation/generator/DataModelInterfaceGenerator/generateDataModelInterface/SampleInterface.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGeneratorTest.java, tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGeneratorTest.java
I've adjusted data model generation process:
1. Interface creation was made optional.
2. If data model has not interface, the fields constants appears in the data model.
3. Adjusted getters and setters annotations for new behaviour.  
4. For setters made return type void.
5.  Added set and get null.
6. Added type for method parameters.
7. Added better description for annotations.
=> Adjust data model generation

resources/fileTemplates/internal/Magento Data Model Interface.php.ft, resources/fileTemplates/internal/Magento Data Model.php.ft, src/com/magento/idea/magento2plugin/actions/generation/data/DataModelData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java, testData/actions/generation/generator/DataModelGenerator/generateDataModelWithoutInterface/Sample.php, testData/actions/generation/generator/DataModelInterfaceGenerator/generateDataModelInterface/SampleInterface.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGeneratorTest.java, tests/com/magento/idea/magento2plugin/actions/generation/generator/DataModelInterfaceGeneratorTest.java
**Data model generation integration with the entity manager:**
=> Data model generation integration with entity manager

resources/fileTemplates/internal/Magento Data Model Interface.php.html, resources/fileTemplates/internal/Magento Data Model.php.html
In this PR I've added descriptions for the internal file templates **Magento Data Model** and **Magento Data Model Interface**.
**Testing was performed on the version IDE 2020.1**
=> Added templates descriptions for Magento Data Model and Magento Data Model Interface

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Get List Query Model.php.ft, resources/fileTemplates/internal/Magento Get List Query Model.php.html, resources/fileTemplates/internal/Magento UI Component Custom Data Provider Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/data/GetListQueryModelData.java, src/com/magento/idea/magento2plugin/actions/generation/data/UiComponentDataProviderData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/GetListQueryModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java, src/com/magento/idea/magento2plugin/magento/files/UiComponentDataProviderPhp.java, src/com/magento/idea/magento2plugin/magento/files/queries/GetListQuery.java, src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java, testData/actions/generation/generator/QueryModelGenerator/generateGetListQueryModelFile/GetListQuery.php, testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateCustomDataProvider/GridDataProvider.php, testData/actions/generation/generator/UiComponentGridDataProviderGenerator/generateDataProviderWithInjectedGetListQuery/GridDataProvider.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/QueryModelGeneratorTest.java, tests/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentGridDataProviderGeneratorTest.java
1. Added GetListQuery model generation.
2. Injected GetListQuery into Data Provider
3. Added GetListQuery model generation test
4. Extended Data Provider generation with the new test case
=> Add query service generation and providing it to data provider

CHANGELOG.md, resources/phpstorm.meta.php/di-autocomplete.php
This PR adds extended **.phpstorm.meta.php** for more convenient autocomplete.
1. Fixes magento/magento2-phpstorm-plugin#403
=> [Backport 3.1.0] Extend .phpstorm.meta.php for more convenient autocomplete

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Entity Save Controller Class.php.ft, resources/fileTemplates/internal/Magento Entity Save Controller Class.php.html, src/com/magento/idea/magento2plugin/actions/generation/data/SaveEntityControllerFileData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityControllerFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/DirectoryGenerator.java, src/com/magento/idea/magento2plugin/magento/files/actions/SaveActionFile.java, src/com/magento/idea/magento2plugin/magento/packages/HttpMethod.java, src/com/magento/idea/magento2plugin/magento/packages/code/BackendModuleType.java, src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java, testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithInterfaceFile/Save.php, testData/actions/generation/generator/SaveEntityActionGenerator/generateSaveEntityActionWithoutInterfaceFile/Save.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityActionGeneratorTest.java
I've created the generator for the save controller.
=> added generator for save controller

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/indexes/FixtureIndex.java, src/com/magento/idea/magento2plugin/linemarker/php/TestFixtureLineMarkerProvider.java, src/com/magento/idea/magento2plugin/magento/files/TestFixture.java, testData/linemarker/php/FixtureLinemarkerRegistrar/magentoApiDataFixtureHaveLinemarker/Test.php, testData/linemarker/php/FixtureLinemarkerRegistrar/magentoDataFixtureHaveLinemarker/Test.php, testData/project/magento2/dev/tests/integration/testsuite/Magento/Catalog/_files/test_fixture.php, tests/com/magento/idea/magento2plugin/linemarker/php/TestFixtureLinemarkerRegistrarTest.java
Added line markers to @magentoDataFixture and @magentoApiDataFixture PHPDoc tag values for easier navigation from a test class to a fixture file.
1. Fixes magento/magento2-phpstorm-plugin#40
=> Added linemarkers for test fixtures

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java
Improved UX by adding autocompletion for entity name dependent fields.
=> Improved UX by adding autocompletion for entity name dependent fields

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Improved UX for entity manager form. Added UI components tab toggling depending on Create Admin UI Components checkbox value.
Improving was suggested by @eduard13 in the https://github.com/magento/magento2-phpstorm-plugin/pull/483
=> Added ui components tab toggling

CHANGELOG.md, src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java, src/com/magento/idea/magento2plugin/util/RegExUtil.java, testData/project/magento2/vendor/magento/module-catalog/test_event/TestObserver.php, testData/reference/xml/ObserverReferenceRegistrar/observerInstanceDirectorySnakeCaseMustHaveReference/events.xml, tests/com/magento/idea/magento2plugin/reference/xml/ObserverReferenceRegistrarTest.java
1. Fixes magento/magento2-phpstorm-plugin#464
=> 464: fixed reference navigation for classes under directories with underscores

CHANGELOG.md, src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
The issue was reproduced on the app/design directory.
1. Fixes magento/magento2-phpstorm-plugin#495
=> 495: Fixed the array access exception when using copy path

CHANGELOG.md, src/com/magento/idea/magento2plugin/completion/provider/PhpClassCompletionProvider.java
Test on actual project. 
1. Fixes magento/magento2-phpstorm-plugin#502
ℹ️ In order to apply the fix, the **reindexing** has to be run.
=> 502: Fixed - Class completion doesn't display interfaces.

CHANGELOG.md, src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java, testData/inspections/xml/ModuleDeclarationInModuleXmlInspection/setupVersionNotErrorMessageInEditableModule/app/code/Test/TestModule/etc/module.xml, tests/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspectionTest.java
I've fixed the bug invalid check 'setup_version'.
=> Fixed bug invalid check setup_version

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/util/ProcessWorker.java
1. fixed multiple firing of generation action if the user clicks the OK button a few times
2. disabled the OK and Cancel buttons until a process is finished
3. run generation process in the separate thread (before: UI interface was blocked until the generation is finished)
4. added beautiful cursor that shows that process is running
The main problem:
After the enhancement:
There is on the GIF image an ugly cursor because it is rotating and cannot be captured by the screencasting app:
In the reality it has a pretty nice look:
=> Enhanced UX with generation process, generation in the separate thread (non-blocking UI), fixed multiple action listener firing

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
This PR aims to focus on the Entity Name field, after opening the New Entity dialog. This will speed up entering the entity data, by not being needed to make 1 extra click to the input.
N/A
=> Focusing the entity name field after opening the Entity dialog 

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
Added navigation to the tab with an error that occurred on a field.
=> Added navigation to tab with error on field

src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java, src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
The duplication plugin warning is shown when disabling a plugin via `di.xml`
This should be shown only for active plugins. Disabled plugins should be skipped.
=> Fixed incorrect duplication warning for disabled plugin in di.xml

resources/fileTemplates/internal/Magento Source Model Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java, src/com/magento/idea/magento2plugin/actions/generation/data/SourceModelData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/EavAttributeInputItemListener.java, src/com/magento/idea/magento2plugin/actions/generation/generator/SourceModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/AttributeMapperFactory.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java, src/com/magento/idea/magento2plugin/magento/files/SourceModelPhp.java, src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeInput.java, src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeScope.java, src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeSourceModel.java, src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeType.java, src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttribute.java, src/com/magento/idea/magento2plugin/magento/packages/eav/EavEntity.java, src/com/magento/idea/magento2plugin/magento/packages/uicomponent/AvailableSourcesByInput.java, testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php, testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php, testData/actions/generation/generator/SourceModelGenerator/generateFile/CustomSourceModel.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java, tests/com/magento/idea/magento2plugin/actions/generation/generator/SourceModelGeneratorTest.java
Added possibilities choose or generate source model according to eav attribute input.
1. Generate product attribute data patch without source model:
https://user-images.githubusercontent.com/29776509/114182248-15aa2080-994b-11eb-8391-6f09b3a2b1a8.mp4
2. Choose source model for some inputs:
https://user-images.githubusercontent.com/29776509/114182381-383c3980-994b-11eb-955a-bb2f6210db40.mp4
3. Generate source model:
https://user-images.githubusercontent.com/29776509/114182455-4d18cd00-994b-11eb-81c2-283f6a071cac.mp4
https://user-images.githubusercontent.com/29776509/114182480-52761780-994b-11eb-89eb-1c526db19033.mp4
1. Fixes magento/magento2-phpstorm-plugin#532
=> Added source model generation for EAV attribute input

src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
- JS and CSS support for Copy Magento Path action.
- logic and simplified flow overall.
1. Fixes magento/magento2-phpstorm-plugin#414
=> JS and CSS support for Copy Magento Path action

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft, resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/data/EavEntityDataInterface.java, src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/ApplyToVisibleListener.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/annotation/RuleRegistry.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/validator/rule/CommaSeparatedStringRule.java, src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java, src/com/magento/idea/magento2plugin/indexes/IndexManager.java, src/com/magento/idea/magento2plugin/magento/files/ProductTypeXml.java, src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttribute.java, src/com/magento/idea/magento2plugin/stubs/indexes/xml/ProductTypeIndex.java, src/com/magento/idea/magento2plugin/util/RegExUtil.java, src/com/magento/idea/magento2plugin/util/magento/GetProductTypesListUtil.java, testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java
Added possibility set `apply_to` property for product  eav attribute. 
There are two variants how to use this property in data patch generation:
1. Apply attribute for all available product types in the system:
If  `Apply to all products types` selected no specific product type will be specified for the attribute.
2. Specify product types:
Unselect `Apply to all products types`, and it will be possible to specify product types:
After that will be generated data patch with specified product types:
1. Fixes magento/magento2-phpstorm-plugin#539
=> 539 add apply to property

resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/data/ProductEntityData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/AttributeSourcePanelComponentListener.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/AttributeSourceRelationsItemListener.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/OptionsPanelVisibilityChangeListener.java, src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/GetAttributeOptionPropertiesUtil.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/eav/ProductAttributeMapper.java, src/com/magento/idea/magento2plugin/magento/packages/eav/AttributeSourceModel.java, src/com/magento/idea/magento2plugin/magento/packages/eav/EavAttribute.java, testData/actions/generation/generator/EavAttributeSetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGeneratorTest.java
Added possibility set options.  We can add options only if input type selected `multi-select` or `select` and didn’t set source model. 
For example  in this case we can’t  see options pane:
If we set source model as `Without Source Model` we can see options panel here:
Now try to set options without sort orders: 
After generation we will see next data patch file:
After `bin/magento setup:upgrade` command execution let's check the attribute in admin panel:
As we can see, product options works as we expected.  On the product edit page it works as expected also:
Let's do the same but with sort ordered option: 
Generated file:
Attribute in admin panel:
1. Fixes magento/magento2-phpstorm-plugin#545
**Contribution …
=> Added possibility to set options

gradle-tasks/staticChecks.gradle
This PR https://github.com/magento/magento2-phpstorm-plugin/pull/553 fixed the CI building but caused a new problem for the local environment. The rulesMinimumPriority setting property doesn’t work for the runIde Gradle task:
This is not a required setting. It is better to remove it at all.
=> Completely removed unknown property for pmd extension

resources/fileTemplates/internal/Magento Eav Attribute Data Patch Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/generator/EavAttributeSetupPatchGenerator.java, src/com/magento/idea/magento2plugin/magento/packages/eav/EavEntity.java, testData/actions/generation/generator/CategoryAttributePropertySetupPatchGenerator/generateFile/AddTestAttributeCategoryAttribute.php, testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFile/AddTestAttribute.php, testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithApplyToAttribute/AddAppliedToAttribute.php, testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithBooleanSourceModel/AddBooleanInputAttributeAttribute.php, testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithGeneratedSourceModel/AddAttributeWithCustomSourceAttribute.php, testData/actions/generation/generator/ProductAttributePropertySetupPatchGenerator/generateFileWithOptions/AddAttributeWithOptionsAttribute.php
This PR aims to bring multiple improvements to EAV generators:
- Entity Type should be imported
- Removed not needed constructor description
- Reordered the DataPatch methods
- Updated tests
N/A
=> Multiple improvements to EAV generators

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/AttributeCodeAdapter.java
Implementing change request:
> 1. Change a bit the order of fields. First field should be Label, based on which the Attribute Code should be autocompleted
> 2. Provide a fields' validation as we did for Entity Generator
> 3. Pay attention at the following PR, as it also actual in scope of Product/Category Attribute generators
> 4. We should be more strict with Group, because if we enter My Group, then Magento generates it as my-group, however the generator adds it as my_group in ui_component form file
1. Changed order of fields for Product and Category entity attribute generation, Attribute Code field autocompletes based on Label field:
2. Fixed fields validation:
3. Fixed tables editing bug
4. We change Group input only for ui_component (for fieldset name) but …
=> Refactored and improved EAV attribute generators

CHANGELOG.md, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java
There is an issue detected in the entity creator feature. If you want to create entity with "double" name like TestEntity, new entity layout and edit entity layout inside it have wrong names:
This PR created to fix this issue. The result:
=> Fixed wrong new entity layout name and edit entity layout name inside it

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/project/diagnostic/DefaultErrorReportSubmitter.java, src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java, src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueUrlBuilderUtil.java
**Description** (*) 
When we want to report some issues by the diagnostic feature, we can get the next output on the GitHub side:
It is caused because generated URI on the plugin side didn't consider max allowed URI length on the GitHub side. If the stack trace for an error is too long, we could have such an error while trying to report an issue. I have fixed that issue:
Also was found and fixed names for registered templates: Magento Web API XML and Web API Interface.
=> Fixed issue with too long URI for generated bug report by diagnostic feature

resources/fileTemplates/code/GitHub New Bug Issue Body Template.txt.ft, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewInterfaceForServiceDialog.java, src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
Added OS, PhpStorm/Intellij version, Plugin Version information to diagnostic report.
=> Diagnostic improvement

src/com/magento/idea/magento2plugin/actions/generation/generator/DataModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityByIdCommandGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/DeleteEntityControllerFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/EditEntityActionGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/EntityDataMapperGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/FormGenericButtonBlockGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/GetListQueryModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/GridActionColumnFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/IndexActionGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleCollectionGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleResourceModelGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/NewActionEntityControllerFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/PhpFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityCommandGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/SaveEntityControllerFileGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentDataProviderGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/php/WebApiInterfaceGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassGeneratorUtil.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/PhpClassTypesBuilder.java, src/com/magento/idea/magento2plugin/util/RegExUtil.java
It is an improvement for the tool that simplifies file properties definition. 
The main points of this enhancement:
1. extract initialisation of the PhpClassTypesBuilder instance to the base class for all PHP generators (PhpFileGenerator)
2. extract file attributes merging and the "USES" attribute definition to the base class
3. simplifying access to set properties and types through the one method
Before we had to call the appendProperty method to add simple property and append to add a type. Now we can use the append method for both cases. There is the syntax/metadata for this method:
``` java
public PhpClassTypesBuilder append(final @NotNull String propertyName, final @NotNull String propertyValue, final boolean isAddToImports) {...}
```
To add a simple property we …
=> Simplified file properties definition for the php file generation

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewInterfaceForServiceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewWebApiDeclarationDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java
Developed autofocus on the first (in most cases) field for all existing custom dialogue forms.
The main place where focusing declaration occurs is the constructor of a dialogue. 
Focusing should be called in the **componentShown** method of the **ComponentListener** interface instance. 
To simplify and make a field focusing shortly I've created the **FocusOnAFieldListener** implementation of the **ComponentListener** interface as an inner class of the **AbstractDialog**. Also, I added detailed annotation on how to use it:
The result for one of the dialogues:
=> Autofocus on a field for all existent dialogs

resources/fileTemplates/code/Magento Plugin After Method.php.ft, resources/fileTemplates/code/Magento Plugin Around Method.php.ft, resources/fileTemplates/code/Magento Plugin Before Method.php.ft, src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/code/PluginMethodsGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/code/util/ConvertPluginParamsToPhpDocStringUtil.java, src/com/magento/idea/magento2plugin/actions/generation/generator/code/util/ConvertPluginParamsToString.java, src/com/magento/idea/magento2plugin/actions/generation/util/FillTextBufferWithPluginMethods.java, src/com/magento/idea/magento2plugin/util/php/PhpTypeMetadataParserUtil.java, testData/actions/generation/generator/PluginClassGenerator/generatePluginClassFile/TestPlugin.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGeneratorTest.java
I've prettified the plugin generation feature.
1. fixed empty line after a class opening tag and before plugin method
2. fixed useless FQCN for subject method argument + in the PHP DOC
3. fixed wrong argument name in the PHP DOC for after plugin's original method argument
4. additionally fixed wrong null type in the PHP DOC for original method arguments and return type (not mentioned in issue #605, for example: ?int or ?SomeType that actually should be int|null and SomeType|null)
5. additionally fixed wrong returning for void plugin methods
5. additionally added an improvement to render strict type for plugin method return
1. Fixes magento/magento2-phpstorm-plugin#605
=> Fixed plugin generation issues

src/com/magento/idea/magento2plugin/indexes/XmlIndex.java
Fixed casting exception and refactored code. Also, there was reported an issue in the plugin slack channel by Laura Folco, that the plugin no longer indicates when a method/class has plugins. I believe that this will fix that problem. 
1. Fixes magento/magento2-phpstorm-plugin#608
=> Fixed casting exception, refactored code

build.gradle, resources/META-INF/plugin.xml
Specified phpPluginVersion in the Gradle wasn't actually built, so the plugin won't work if the same version is specified for since-build (production) attribute.
=> PHP plugin version alignment (for v.4.0.1)

build.gradle, resources/META-INF/plugin.xml
Specified phpPluginVersion in the Gradle wasn't actually built, so the plugin won't work if the same version is specified for since-build (production) attribute.
=> PHP plugin version alignment (for v.4.1.0)

src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java
Fixed NullPointerException for InjectAViewModelAction#getElement method call.
1. Fixes magento/magento2-phpstorm-plugin#653
=> [4.1.1-develop] Bug-653: Fixed NullPointerException for InjectAViewModelAction#getElement

src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
I've successfully reproduced reported bug:
The result after fixing it:
1. Fixes magento/magento2-phpstorm-plugin#659
=> [4.1.1-develop] Fixed Bug with inspection observer null pointer for event name attribute

src/com/magento/idea/magento2plugin/magento/packages/code/MagentoVersion.java, src/com/magento/idea/magento2plugin/project/Settings.java, src/com/magento/idea/magento2plugin/project/SettingsForm.form, src/com/magento/idea/magento2plugin/project/SettingsForm.java, src/com/magento/idea/magento2plugin/project/util/GetMagentoVersionUtil.java, src/com/magento/idea/magento2plugin/util/magento/MagentoVersionUtil.java
This pull request adds the ability to display the Client's Platform Version in the settings form. For:
"magento/product-enterprise-edition" -> "Adobe Commerce"
"magento/product-community-edition" -> "Magento Open Source"
If the platform has not been defined then "Platform Version:" will be shown.
This will help the user to quickly understand what version of Magento2 is used.
=> Update Platform Version In Setting Form

src/com/magento/idea/magento2uct/execution/GenerateUctReportCommand.java, src/com/magento/idea/magento2uct/execution/output/Summary.java, src/com/magento/idea/magento2uct/inspections/UctInspectionManager.java, src/com/magento/idea/magento2uct/settings/UctSettingsService.java, src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java, src/com/magento/idea/magento2uct/util/inspection/SortDescriptorResultsUtil.java, src/com/magento/idea/magento2uct/versioning/VersionStateManager.java
- refactored code, added some improvements
- all errors sorted by their line number
1. Fixes magento/magento2-phpstorm-plugin#768
=> UCT-768: Sort errors by lines

src/com/magento/idea/magento2plugin/actions/generation/InjectAViewModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java, src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
Fixed NullPointerException for InjectAViewModelAction#getElement method call.
1. Fixes magento/magento2-phpstorm-plugin#653
=> [4.2.0-develop] Bug-653: Fixed NullPointerException for InjectAViewModelAction#getElement

src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java
I've successfully reproduced reported bug:
The result after fixing it:
1. Fixes magento/magento2-phpstorm-plugin#659
=> [4.2.0-develop] Bug-659: Fixed NullPointerException for a name attribute of the event tag and code style fixes

src/com/magento/idea/magento2plugin/reference/provider/PluginReferenceProvider.java, src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java
I've successfully reproduced reported bug:
The result of the bug fix:
1. Fixes magento/magento2-phpstorm-plugin#663
=> [4.2.0-develop] Bug-663: Fixed NullPointerException for PluginReferenceProvider

src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Fixed ArrayIndexOutOfBoundsException exception when used Copy Path/Reference action on the requirejs-config.js file.
**Successfully reproduced before starting fixing it:**
**Result:**
1. Fixes magento/magento2-phpstorm-plugin#798
=> Bugfix-798: Fixed ArrayIndexOutOfBoundsException exception

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAPluginDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/CreateAnObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/InjectAViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewInterfaceForServiceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewWebApiDeclarationDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideClassByAPreferenceDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideInThemeDialog.java, src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java, src/com/magento/idea/magento2uct/ui/ReindexDialog.java
Fixed issue with an overlay stays over the editor after any plugin dialog window is closed after successfully finished operation, cancelation, error showing.
**Successfully reproduced issue:**
**Result:**
1. Fixes magento/magento2-phpstorm-plugin#667
=> Bug-667: Fixed dialog disposition issue

src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java, src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java, src/com/magento/idea/magento2plugin/linemarker/php/WebApiLineMarkerProvider.java
Fixed stack overflow error for the next line-marker providers:
- com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider
- com.magento.idea.magento2plugin.linemarker.php.PluginTargetLineMarkerProvider
- com.magento.idea.magento2plugin.linemarker.php.WebApiLineMarkerProvider
**The bug was successfully reproduced by the next steps:**
1. created new class A
2. created new class B
3. added plugins for class A
4. made class A extends class B
5. made class B extends class A
**The results after fixing it:**
1. Fixes magento/magento2-phpstorm-plugin#765
=> Bugfix/765: Fixed stack overflow error for line-marker providers

src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
Fixed stub ids not found for key in index. Refactored code in the related class.
**The bug reproduced before fixing it:**
**The result of bug-fixing:**
1. Fixes magento/magento2-phpstorm-plugin#666
=> [Bug] 666: Fixed stub ids not found for key in index

src/com/magento/idea/magento2plugin/stubs/indexes/js/RequireJsIndex.java
Fixed failed to build requirejs-config.js files index.
**Bug was reproduced before fixing:**
**The result of fixing it:**
1. Fixes magento/magento2-phpstorm-plugin#645
=> Bugfix-645: Fixed failed to build require-js index

src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java
Fixed empty psi elements in the plugin inspections.
**The bug is reproduced before fixing it:**
**The result of fixing:**
**The same issue is found for the PHPStorm inspection:**
**For clean testing it is should be disabled before testing bugfix:**
**I've opened an issue in the PHPStorm regarding mentioned PHPStorm inspection:**
https://youtrack.jetbrains.com/issue/WI-64186
1. Fixes magento/magento2-phpstorm-plugin#739
=> Bugfix-739: Fixed empty psi elements in the plugin inspections

src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java
Fixed empty PSI elements must not be passed to createDescriptor for the ModuleDeclarationInModuleXmlInspection inspection.
**The bug was reproduced before fixing it:**
**The result after the bug fixing:**
1. Fixes magento/magento2-phpstorm-plugin#685
=> [Bugfix:685] Fixed empty psi element in module xml inspection

src/com/magento/idea/magento2plugin/linemarker/php/WebApiLineMarkerProvider.java
Fixed java.lang.NullPointerException in the WebApiLineMarkerProvider for firstSortOrder.compareTo.
**Issue was reproduced before fixing it:**
**The result after fixing it:**
1. Fixes magento/magento2-phpstorm-plugin#646
=> [Bug] 646: Fixed NullPointerException for the firstSortOrder.compareTo

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/DbSchemaXmlGenerator.java
Fixed Invalid column types provided exception during db_schema.xml file generation.
**Bug was successfully reproduced before fixing it:**
**The results after the bug fixing:**
1. Fixes magento/magento2-phpstorm-plugin#626
=> [Bug] 626: Fixed Invalid column types provided exception during db_schema.xml file generation

CHANGELOG.md
Updated changelog before releasing 4.2.1.
=> [Release-4.2.1] Preparing release 4 2 1

build.gradle, src/com/magento/idea/magento2plugin/linemarker/php/GraphQlResolverUsageLineMarkerProvider.java
Fixed java.lang.NoClassDefFoundError for com.intellij.lang.jsgraphql.GraphQLIcons.
**Successfully reproduced:**
**Result:**
1. Fixes magento/magento2-phpstorm-plugin#838
=> 838: Fixed java.lang.NoClassDefFoundError for com.intellij.lang.jsgraphql.GraphQLIcons

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json, testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json, testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFileWithoutDependencies/composer.json, tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGeneratorTest.java
According to [Magento Devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/composer-integration.html#package-name) each module should be named with a module prefix in the composer.json. Added logic which adding prefix the module to package-name in composer.json
Issue was reproduced before fixing it:
When we create a new module and set Vendor_Test, it will be named vendor/test.
The result after fixing it:
1. Fixed [Add "module" prefix to module name in composer.json](https://github.com/magento/magento2-phpstorm-plugin/issues/698) #<698>
=> 698: Add "module" prefix to module name in composer.json

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/util/magento/GetModuleNameByDirectoryUtil.java
Fixed java.lang.NullPointerException when opening new cron job dialog for an invalid Magento 2 module.
**The bug was reproduced before fixing it:**
**Behaviour after bug fixing (for an invalid module structure):**
The cron job name is not auto-populated as it cannot be resolved without valid module structure.
**Behaviour after bug fixing (for a valid module structure):**
The cron job name is auto-populated.
1. Fixes magento/magento2-phpstorm-plugin#825
=> 825: null pointer exception new cronjob dialog suggest cronjob name

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/generator/PluginClassGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/util/FileFromTemplateGenerator.java
Fixed java.lang.Throwable: when an IOException is thrown during new plugin generation.
**The bug was reproduced programmatically:**
**Obsolete popup with detailed message was eliminated:**
**Main popup with an general error was updated with detailed message IF it is known in particular case:**
**before:**
**after:**
1. Fixes magento/magento2-phpstorm-plugin#760
=> 760: fixed throwable when io exception is thrown during plugin generation

src/com/magento/idea/magento2plugin/actions/generation/CreateAPluginAction.java, src/com/magento/idea/magento2plugin/inspections/php/util/PhpClassImplementsNoninterceptableInterfaceUtil.java
Fixed slow operations are prohibited on EDT when calling update method on the CreateAPluginAction.
**This issue was reproduced before fixing it:**
This exception was throwing while accessing context menu under a php class method name during reindexing process.
1. Fixes magento/magento2-phpstorm-plugin#651
=> 651: slow operations are prohibited on EDT

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCLICommandAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewGraphQlResolverAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewViewModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCLICommandDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewGraphQlResolverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
Enhanced error outputting for the new Magento 2 CLI command generation.
1. Fixes magento/magento2-phpstorm-plugin#872
=> 872: enhanced new cli command dialog UX

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java
Enhanced error outputting for the new Magento 2 Block generation.
1. Fixes magento/magento2-phpstorm-plugin#864
=> 864: enhanced a new block dialog UX

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java
Enhanced error outputting for the new Magento 2 Controller generation.
1. Fixes magento/magento2-phpstorm-plugin#867
=> 867: enhanced new controller dialog UX

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
Enhanced error outputting for the new Magento 2 Cron Job generation.
1. Fixes magento/magento2-phpstorm-plugin#868
=> 868: enhanced new cron job dialog UX

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java
Enhanced error outputting for the new Magento 2 Cron Group generation.
1. Fixes magento/magento2-phpstorm-plugin#869
=> 869: enhanced new cron group dialog UX

src/com/magento/idea/magento2plugin/actions/generation/NewBlockAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewControllerAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronGroupAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewCronjobAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewViewModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewBlockDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewControllerDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronGroupDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCronjobDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewViewModelDialog.java
Enhanced error outputting for the new Magento 2 View Model generation.
1. Fixes magento/magento2-phpstorm-plugin#870
=> 870 enhance new view model dialog ux

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentFormAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentGridAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
Enhanced error outputting for the new Magento 2 UI Form generation.
1. Fixes magento/magento2-phpstorm-plugin#879
=> 879 enhance new UI form dialog ux

src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
Enhanced error outputting for the new Magento 2 models generation.
1. Fixes magento/magento2-phpstorm-plugin#874
=> 874: enhanced new models dialog UX

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
Enhanced error outputting for the new Magento 2 db schema generation.
1. Fixes magento/magento2-phpstorm-plugin#877
=> 877 enhance new db schema dialog ux

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/actions/generation/NewDataModelAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewDbSchemaAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewEmailTemplateAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewMessageQueueAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewModelsAction.java, src/com/magento/idea/magento2plugin/actions/generation/NewUiComponentGridAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDbSchemaDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEmailTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
Enhanced error outputting for the new Magento 2 UI Grid generation.
1. Fixes magento/magento2-phpstorm-plugin#878
=> 878: enhanced new UI grid dialog UX

src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleControllerClassGenerator.java
1. Fixes magento/magento2-phpstorm-plugin#857
=> 857: fixed error when class already exists

src/com/magento/idea/magento2plugin/actions/generation/generator/MessageQueueClassGenerator.java, src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
1. Fixes magento/magento2-phpstorm-plugin#842
=> 842 incomplete trailing escape

src/com/magento/idea/magento2plugin/indexes/ModuleIndex.java
1. Fixes magento/magento2-phpstorm-plugin#866
=> 866: IndexNotReadyException while opening a context menu

src/com/magento/idea/magento2plugin/stubs/indexes/WebApiTypeIndex.java
Fixed PsiPlainTextFileImpl cannot be cast to class XmlFile in WebApiTypeIndex.
1. Fixes magento/magento2-phpstorm-plugin#654
=> 654: fixed class cast exception in web api type index

src/com/magento/idea/magento2plugin/inspections/php/ModuleDeclarationInRegistrationPhpInspection.java, src/com/magento/idea/magento2plugin/magento/packages/code/FrameworkLibraryType.java, testData/project/magento2/vendor/magento/framework/Component/ComponentRegistrar.php
Fixed module name declaration inspection flags valid code.
**Issue was reproduced before fixing it:**
**Result:**
1. Fixes magento/magento2-phpstorm-plugin#834
=> 834: module name declaration inspection flags valid code

src/com/magento/idea/magento2plugin/inspections/xml/PluginDeclarationInspection.java
I fixed the current check.
Now if the type is specified for this plugin, the error will not be displayed
1. Fixes magento/magento2-phpstorm-plugin#590
=> 590: The plugin inspection does not work correctly

README.md
Updated readme file with information about sandbox creation.
1. Fixes magento/magento2-phpstorm-plugin#914
=> 914: Updated readme file with information about sandbox creation

src/com/magento/idea/magento2plugin/linemarker/xml/LineMarkerXmlTagDecorator.java
I think we have two variants. We should set this method how deprecated and never use xmlTag.checkAdd() or create another realisation for it. I found service CheckUtil which has realisation checkWritable (similar checkAdd) for PsiElement. 
1. Fixes Eliminate LineMarkerXmlTagDecorator#checkAdd usage #899
=> 899: lineMarkerXmltag Decorator#checkadd

src/com/magento/idea/magento2plugin/linemarker/xml/LineMarkerXmlTagDecorator.java
I think we have two variants. We should set this method how deprecated and never use xmlTag.checkDelete() or create another realisation for it. I found service CheckUtil which has realisation checkWritable (similar checkDelete) for PsiElement. 
1. Fixes Eliminate LineMarkerXmlTagDecorator#checkDelete usage #900
=> 900: Changed realization for function checkDelete using of CheckUtil.

src/com/magento/idea/magento2plugin/stubs/indexes/graphql/GraphQlResolverIndex.java
Fixed bug ClassCastException.
1. Fixes magento/magento2-phpstorm-plugin#907
=> 907: Fix class cast exception

src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java, testData/actions/generation/generator/ModuleComposerJsonGenerator/generateFileInRoot/composer.json, testData/actions/generation/generator/ModuleComposerJsonGenerator/generateModuleFile/composer.json
Fixed usage of deplicated and file upload
1. Fixes magento/magento2-phpstorm-plugin#913
=> 913: Fixed parse usage

src/com/magento/idea/magento2plugin/linemarker/SearchGutterIconNavigationHandler.java, src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java
Added **"Open In Find Tool Window"** action to the **"Navigate to plugins"** linemarker.
1. Fixes magento/magento2-phpstorm-plugin#833
=> 833: Added Open In Find Tool Window action to the Navigate to plugins linemarker

src/com/magento/idea/magento2plugin/reference/provider/PhpClassReferenceProvider.java
**Description** (*):
Fixed general Exception in the PhpClassReferenceProvider while accessing phpIndex.getAnyByFQN(classFQN).
1. Fixes magento/magento2-phpstorm-plugin#932
=> 932: Fixed general exception while accessing phpIndex.getAnyByFQN(classFQN)

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java, src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java, src/com/magento/idea/magento2plugin/lang/roots/MagentoTestSourceFilter.java
Introduced new predefined search scope group (**Magento**) and search scope (**All Files Except Tests**).
It works as **All Places** search scope except ignoring php test classes.
1. Fixes magento/magento2-phpstorm-plugin#620
=> 620: Introduced custom search scope to exclude test files from search

src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java, src/com/magento/idea/magento2plugin/magento/files/Observer.java
Added references on possible event manager classes or interfaces:
- Magento\Framework\Event\ManagerInterface -> origin
- Magento\Framework\Event\Manager
- Magento\Framework\EntityManager\EventManager
- Magento\Staging\Model\Event\Manager
1. Fixes magento/magento2-phpstorm-plugin#853
=> 853: Fix observer action visibility

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/lang/injection/UiComponentSyntaxInjector.java
Provided uiComponent registration syntax highlighting inside `<script type="x-magento-init">` tags.
1. Fixes magento/magento2-phpstorm-plugin#276
=> 276: Added uiComponent registration syntax highlighting as JSON

src/com/magento/idea/magento2plugin/actions/generation/dialog/AbstractDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/prompt/PlaceholderInitializerUtil.java
Developed flexible way to add placeholders to a dialog window fields that inherited from the JTextComponent.
1. Fixes magento/magento2-phpstorm-plugin#598
=> 598: Added placeholder to dialog window

src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
Added additional check if the Magento 2 integration is enabled for Magento scopes.
1. Fixes magento/magento2-phpstorm-plugin#943
=> 943: added integration enabled check for custom search scope

src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
1. Fixes magento/magento2-phpstorm-plugin#963
=> 963: Bug during composer json generation

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/indexes/IndexManager.java, src/com/magento/idea/magento2plugin/reference/provider/mftf/TestExtendedByReferenceProvider.java, src/com/magento/idea/magento2plugin/reference/xml/XmlReferenceContributor.java, src/com/magento/idea/magento2plugin/stubs/indexes/mftf/TestExtendsIndex.java
Added references for the extended by MFTF tests:
Those references appears when clicking by the MFTF test name.
1. Fixes magento/magento2-phpstorm-plugin#452
=> 452: Added extended by references for the MFTF tests

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento System XML.xml.ft, resources/fileTemplates/internal/Magento System XML.xml.html, src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewAclXmlAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewConfigXmlAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewDiXmlAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewRoutesXmlAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewSystemXmlAction.java, src/com/magento/idea/magento2plugin/actions/context/xml/NewWebapiXmlAction.java, src/com/magento/idea/magento2plugin/completion/xml/XmlCompletionContributor.java, src/com/magento/idea/magento2plugin/magento/files/ModuleSystemXmlFile.java, src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java, tests/com/magento/idea/magento2plugin/completion/xml/BackendModelXmlCompletionRegistrarTest.java, tests/com/magento/idea/magento2plugin/completion/xml/SourceModelXmlCompletionRegistrarTest.java
Added system.xml file generation in the target context directory.
1. Fixes magento/magento2-phpstorm-plugin#977
=> 977: Added system.xml file in context generation

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Indexer XML.xml.ft, resources/fileTemplates/internal/Magento Indexer XML.xml.html, src/com/magento/idea/magento2plugin/actions/context/xml/NewIndexerXmlAction.java, src/com/magento/idea/magento2plugin/magento/files/ModuleIndexerXmlFile.java
Added indexer.xml file in context generation.
1. Fixes magento/magento2-phpstorm-plugin#986
=> 986: Added indexer.xml file in context generation.

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.form
Added placeholder to UI Component Grid dialog window.
1. Fixes magento/magento2-phpstorm-plugin#1006
=> 1006: Added placeholder to UI Component Grid dialog window

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.form
Added placeholder to UI Component Form dialog window.
1. Fixes magento/magento2-phpstorm-plugin#1007
=> 1007: Added placeholder to UI Component Form dialog window

src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/magento/packages/Package.java, src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Fix showing package name on windows
1. Fixes magento/magento2-phpstorm-plugin#929
=> 929: Fix showing package name on windows

src/com/magento/idea/magento2plugin/magento/packages/UiFormButtonTypeSettings.java, testData/actions/generation/generator/FormButtonBlockGenerator/generateBackButtonBlock/MyBackButton.php, testData/actions/generation/generator/FormButtonBlockGenerator/generateDeleteButtonBlock/DeleteBlock.php, testData/actions/generation/generator/FormButtonBlockGenerator/generateSaveButtonBlock/SaveBlock.php
Updated generating of the "UI form Delete" button.
The sorting for buttons has been changed:
- Back button: 10 
- Delete button: 20
- Save button: 30 
Also, for the Delete button, the on click option changed to use the **sprintf** function instead of the concatenation.
1. Fixes magento/magento2-phpstorm-plugin#1012
=> 1012: Updating generating UI form Delete button

src/com/magento/idea/magento2uct/settings/UctSettingsService.java, src/com/magento/idea/magento2uct/ui/ConfigurationDialog.form, src/com/magento/idea/magento2uct/ui/ConfigurationDialog.java
Added additional fields to UCT configuration dialog. When you click on checkbox "Add additional path to analyse" an additional field "Path To Analyse" will become available for selection.
1. Fixes magento/magento2-phpstorm-plugin#1023
=> 1023: Added an additional path field for UCT configuration dialog (to cover theme folder scanning)

src/com/magento/idea/magento2plugin/actions/CopyMagentoPath.java
Added Images support for Copy Magento Path.
Used ImageIO extension support for images.
1. Fixes magento/magento2-phpstorm-plugin#414
=> 414: Added Images support for Copy Magento Path

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/actions/generation/OverrideFileInThemeAction.java, src/com/magento/idea/magento2plugin/actions/generation/OverrideLayoutInThemeAction.java, src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideLayoutInTheme.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideLayoutInThemeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideLayoutInThemeGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInThemeGenerator.java, src/com/magento/idea/magento2plugin/magento/files/LayoutXml.java, src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
Hello! I changed the behavior for the action menu for overwriting template files.
Now we have one menu and dialog window for templates and less files.
Now plugin copied correctly the files to the selected theme.
I also changed the gear of overwriting the layout files
1. Fixes magento/magento2-phpstorm-plugin#1026
=> Change overwrite templates feature for action menu

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
Fixed issue with wrong references resolved for a class if Magento 2 proxy was generated for it.
In this case the PHPStorm filters references resolved from the `/vendor/` directory if there is any result from the project itself (`generated` folder in this case).
**Before:**
ℹ️ Additional side affect provided in the related issue: #984.
**After:**
1. Fixes magento/magento2-phpstorm-plugin#984
=> 984: Filtered generated folder from reference resolving results

src/com/magento/idea/magento2plugin/actions/generation/util/FillTextBufferWithPluginMethods.java
Eliminated usage of deprecated method Function#getReturnType for class com.magento.idea.magento2plugin.actions.generation.util.FillTextBufferWithPluginMethods.
This functionality works when creating a plugin from the context menu.
https://user-images.githubusercontent.com/89141549/159774081-f0215fe6-ebda-4876-a5fe-8bd56cd767ac.mp4
**Type bool:**
**Type int:**
**Type string:**
**Type array:**
**Type void:**
**Type string with params:**
**Type array with params:**
**Type string with param string:**
1. Fixes magento/magento2-phpstorm-plugin#1035
=> 1035: removed deprecated Function#getReturnType

resources/fileTemplates/internal/Require Config JS File.js.ft, resources/fileTemplates/internal/Require Config JS File.js.html, src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/OverrideTemplateInThemeDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideInThemeGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/OverrideTemplateInThemeGenerator.java, src/com/magento/idea/magento2plugin/actions/generation/generator/js/RequireJsConfigGenerator.java, src/com/magento/idea/magento2plugin/magento/files/RequireConfigJsFile.java, src/com/magento/idea/magento2plugin/magento/packages/OverridableFileType.java
Hi all! I checked overwriting javascript and styles files and made some changes.
1. Overwriting a template from a module:
2. Overwriting a template from a heme to another theme:
3. Overwriting a js from module to a theme:
4. Overwriting a js file from a theme to another theme:
5. Overwriting a js file from lib/web folder:
6. Overwriting a lib js files from one theme to another works to.
7. Overwriting styles for less and css files:
10. From one theme to another:
1. Fixes magento/magento2-phpstorm-plugin#603
9. Fixes magento/magento2-phpstorm-plugin#602
=> Fixes for overrite for js and css files in theme

CHANGELOG.md
=> 4.3.0 pre release

src/com/magento/idea/magento2plugin/reference/provider/FilePathReferenceProvider.java
Fixed bug that appears when trying to instantiate a new TextRange object by providing an invalid startOffset/endOffset values.
1. Fixes magento/magento2-phpstorm-plugin#1048
=> 1048: Fixed bug with wrong text range

src/com/magento/idea/magento2plugin/actions/context/AbstractContextAction.java, src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java, src/com/magento/idea/magento2plugin/util/RegExUtil.java, src/com/magento/idea/magento2plugin/util/magento/GetMagentoModuleUtil.java
Fixed module context actions are available in the theme context.
1. Fixes magento/magento2-phpstorm-plugin#1010
=> 1010: Fixed module context actions available in the theme

src/com/magento/idea/magento2plugin/lang/psi/search/AllFilesExceptTestsScope.java, src/com/magento/idea/magento2plugin/lang/psi/search/MagentoSearchScopesProvider.java
1. Fixes magento/magento2-phpstorm-plugin#1049
=> 1049: fixed index already disposed in search

src/com/magento/idea/magento2plugin/magento/packages/MagentoComponentManager.java
1. Fixes magento/magento2-phpstorm-plugin#1051
=> 1051 fix already disposed exception

CHANGELOG.md
=> Preparing release 4.3.1

src/com/magento/idea/magento2plugin/actions/comparator/CompareTemplateAction.java
Fixed a bug that caused a bug when comparing files
1. Fixes magento/magento2-phpstorm-plugin#1113
=> 1113: Fixed IllegalArgumentException: Argument for @NotNull parameter 'dataKey' must not be null in CompareTemplateAction

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Module Readme File MD.md.ft, resources/fileTemplates/internal/Magento Module Readme File MD.md.html, src/com/magento/idea/magento2plugin/actions/generation/data/ModuleReadmeMdData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleReadmeMdGenerator.java, src/com/magento/idea/magento2plugin/magento/files/ModuleReadmeMd.java, src/com/magento/idea/magento2plugin/magento/files/ModuleReadmeMdFile.java, testData/actions/generation/generator/ModuleReadmeMdGenerator/generateModuleReadmeMdFile/README.md, tests/com/magento/idea/magento2plugin/actions/generation/generator/BaseGeneratorTestCase.java, tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleReadmeMdGeneratorTest.java
Added option to generate a README.md file during creation of module
https://user-images.githubusercontent.com/20201927/172556445-9f0c4984-9c16-4489-b20e-be268d61290f.mov
1. Fixes magento/magento2-phpstorm-plugin#1016
=> 1016: Add optional generation of README.md during module creation

src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
Fix isMagentoFolderValid method in MagentoBasePathUtil class
1. Fixes magento/magento2-phpstorm-plugin#1124
=> 1124: Fixed PatternSyntaxException: MagentoBasePathUtil.isMagentoFolderValid:35 for Windows styled dir path separator

src/com/magento/idea/magento2plugin/actions/generation/OverrideTemplateInThemeAction.java
Fix NullPointerException in the OverrideTemplateInThemeAction.isOverrideAllowed for virtualFile.getCanonicalPath().
1. Fixes magento/magento2-phpstorm-plugin#1106
=> 1106: Fixed NullPointerException in the OverrideTemplateInThemeAction.isOverrideAllowed for virtualFile.getCanonicalPath()

src/com/magento/idea/magento2plugin/project/diagnostic/github/GitHubNewIssueBodyBuilderUtil.java
Added an additional check for string index in `GitHubNewIssueBodyBuilderUtil` class to prevent a `StringIndexOutOfBoundsException` 
1. Fixes magento/magento2-phpstorm-plugin#1128
=> 1128 fix bug with index in GitHubNewIssueBodyBuilderUtil class

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/actions/context/md/NewReadmeMdAction.java
Added option to generate README.md file from context menu.
https://user-images.githubusercontent.com/20201927/180004479-93f22e55-b0d6-4305-8967-77cbae8e2157.mov
1. Fixes magento/magento2-phpstorm-plugin#1111
=> 1111: Add context dependent action for generation of README.md

src/com/magento/idea/magento2plugin/actions/generation/PluginGenerateMethodHandlerBase.java, src/com/magento/idea/magento2plugin/inspections/php/PluginInspection.java, src/com/magento/idea/magento2plugin/linemarker/php/PluginLineMarkerProvider.java, src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java, src/com/magento/idea/magento2plugin/linemarker/php/data/PluginMethodData.java, src/com/magento/idea/magento2plugin/magento/files/ModuleDiXml.java, src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java, src/com/magento/idea/magento2plugin/stubs/indexes/data/PluginData.java, src/com/magento/idea/magento2plugin/stubs/indexes/data/PluginSetDataExternalizer.java, src/com/magento/idea/magento2plugin/util/magento/plugin/GetTargetClassNamesByPluginClassName.java
It was added by sorting the plugin parkers depending on it's "before" "around" or "after" plugin, and by the sortOrder attribute value.
But it was not included in sorting by the module sequence. Here we should add the parsing `config.php` file and provide an array with the module name and sequence value. Please to implement it was added the note `@TODO` at the the `com.magento.idea.magento2plugin.linemarker.php.PluginLineMarkerProvider.PluginClassCache#getPluginMethods(java.util.List<com.magento.idea.magento2plugin.stubs.indexes.data.PluginData>)`
**Actual results:**
In the first file, you can see the list sorted by sortOrder value and the correct list for the `after` plugin after around.
In the second file, you can see that the vendor plugin, which has no `sortOrder` …
=> 406: added sorting plugin list marker

src/com/magento/idea/magento2plugin/actions/generation/NewModuleAction.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModuleDialog.java
This PR fixes IllegalArgumentException.
1. Fixes magento/magento2-phpstorm-plugin#1142
=> 1142 fix bug IllegalArgumentException in NewModuleAction class

src/com/magento/idea/magento2uct/execution/output/ReportBuilder.java
This pull request (PR) provides, fix bug Invalid file name: '26_Aug_2022_13:11:03-results.json'. The file name format has been changed, now name does not contain reserved characters.
1. Fixes magento/magento2-phpstorm-plugin#1152
=> 1152: Fix bug invalid file name: '26_Aug_2022_13:11:03-results.json'

resources/fileTemplates/includes/MD File Description.md.ft, resources/fileTemplates/includes/MD File Description.md.html, resources/fileTemplates/internal/Magento Module Readme File MD.md.ft, src/com/magento/idea/magento2plugin/actions/context/md/NewReadmeMdAction.java
Implemented next solutions:
- Added check, if the [README.md](http://readme.md/) file is already generated do not show action.
- Added a new code include, to be able generate project-specific [README.md](http://readme.md/) files
1. Fixes magento/magento2-phpstorm-plugin#1141
=> 1141: Add code include, don't show generation action if readme exists

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCategoryEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewCustomerEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewProductEavAttributeDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/eavattribute/EavAttributeDialog.java
Removed content jumps from EAV generators forms.
Product EAV attribute form:
https://user-images.githubusercontent.com/31848341/188474111-59c01c4a-2ec1-474d-bfdb-18f593e68a0b.mp4
Category EAV attribute form:
https://user-images.githubusercontent.com/31848341/188474193-35597fbb-4751-44e0-a97c-9048680cc66b.mp4
Customer EAV attribute form:
https://user-images.githubusercontent.com/31848341/188474365-3af7032a-df9a-4dcd-80fc-a992f9949328.mp4
1. Fixes magento/magento2-phpstorm-plugin#1145
=> 1145: Removed content jumping from EAV generators forms

src/com/magento/idea/magento2plugin/actions/context/CustomGeneratorContextAction.java, src/com/magento/idea/magento2plugin/actions/context/md/NewReadmeMdAction.java, src/com/magento/idea/magento2plugin/actions/context/util/GetTargetElementUtil.java
Fixed that README.md template include is not working for project level.
https://user-images.githubusercontent.com/31848341/188676586-cfd7687e-b87d-4928-aa45-2bc1ebd35e42.mp4
1. Fixes magento/magento2-phpstorm-plugin#1156
=> 1156: Fixed README.md template include is not working for project level

src/com/magento/idea/magento2plugin/actions/generation/CreateAnObserverAction.java, src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java
This pull request (PR) provides, fix bug create an observer for an event doesn't work through the context menu
1. Fixes magento/magento2-phpstorm-plugin#1102
=> 1102: Fix bug create an observer

resources/META-INF/plugin.xml, resources/inspectionDescriptions/InvalidVirtualTypeSourceClassInspection.html, resources/magento2/inspection.properties, src/com/magento/idea/magento2plugin/inspections/xml/InvalidVirtualTypeSourceClassInspection.java
Added inspection to check if type attribute value in the virtual type tag exists.
For an empty value:
For an invalid value:
For a valid value:
1. Fixes magento/magento2-phpstorm-plugin#1100
=> 1100: Added inspection to check if type attr value in the virtual type tag exists

resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java, src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java
This fix allow us to show detailed error messages for users when they enabling plugin. 
Current video demonstrates how it will work:
https://user-images.githubusercontent.com/20201927/189652724-bb4a66b1-762f-4ec2-b68a-d2de870e5990.mov
1. Fixes magento/magento2-phpstorm-plugin#1144
=> 1144: Add checks and detailed error messages during plugin activation

build.gradle, resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
Trying to fix compatibility issues with newer IntelliJ Idea version.
1. Fixes magento/magento2-phpstorm-plugin#1179
=> Fixed new intellij version compatibility issues

resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/actions/context/xml/NewEventsXmlAction.java
This PR adds action to generate events XML files.
1. Fixes magento/magento2-phpstorm-plugin#1175
=> 1175: Add action to generate events.xml file through the context menu

CHANGELOG.md, resources/META-INF/plugin.xml, resources/META-INF/withJsGraphQl.xml, resources/fileTemplates/internal/Magento Customer Eav Attribute Data Patch Class.php.ft, resources/magento2/validation.properties, src/com/magento/idea/magento2plugin/inspections/xml/ObserverDeclarationInspection.java, src/com/magento/idea/magento2plugin/lang/php/MagentoProxyDeclarationFilter.java, src/com/magento/idea/magento2plugin/project/validator/SettingsFormValidator.java, src/com/magento/idea/magento2plugin/util/magento/MagentoBasePathUtil.java, testData/actions/generation/generator/CustomerAttributeSetupPatchGenerator/generateMultiselectAttributeDataPatch/AddMultiselectTestCustomerAttribute.php
Merge last changes from 4.4.0-develop to 4.4.1-develop.
=> Merge 4.4.0 develop into 4.4.1 develop

resources/META-INF/plugin.xml, resources/fileTemplates/internal/Magento Module Observer File.php.ft, resources/fileTemplates/internal/Magento Module Observer File.php.html, src/com/magento/idea/magento2plugin/actions/context/php/NewObserverAction.java, src/com/magento/idea/magento2plugin/actions/generation/ModuleObserverData.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.form, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleObserverGenerator.java, src/com/magento/idea/magento2plugin/magento/files/ModuleObserverFile.java, testData/actions/generation/generator/ModuleObserverGenerator/generateModuleObserverFile/TestClassObserver.php, tests/com/magento/idea/magento2plugin/actions/generation/generator/ModuleObserverGeneratorTest.java
This pull request (PR) provides, creating a new observer template.
**Error message if specified patch name is already exist**
1. Fixes magento/magento2-phpstorm-plugin#1139
=> 1139: Creating a new observer template

src/com/magento/idea/magento2plugin/completion/provider/LayoutBlockCompletionContributor.java, src/com/magento/idea/magento2plugin/completion/provider/LayoutContainerCompletionContributor.java, src/com/magento/idea/magento2plugin/completion/provider/LayoutUpdateCompletionContributor.java, src/com/magento/idea/magento2plugin/completion/provider/UiComponentCompletionProvider.java, src/com/magento/idea/magento2plugin/completion/provider/VirtualTypeCompletionProvider.java, src/com/magento/idea/magento2plugin/generation/php/MagentoTemplatesFactory.java
Fixed several compatibility issues related to usage of unavailable icon constants.
In this PR was used icon constants that compatible with new version of IDE (currently **Intellij IDEA 2022.3 EAP**).
Some details about updated icons. For screenshots previous icons I use stable `4.4.0` version of plugin and new icons marked as `4.4.1-develop` :
1. `PhpIcons.CLASS_ICON` → `AllIcons.Nodes.Class`
2. `PhpIcons.XML_TAG_ICON` → `AllIcons.Nodes.Tag`
3. `PhpIcons.Php_icon` → `PhpIcons.PhpIcon`
PhpIcons.Php_icon is deprecated, if we look at the code we can see that PhpIcons.Php_icon just refers to PhpIcons.PhpIcon. 
Also made some code style improvements  (checkstyles, etc.).
1. Fixes magento/magento2-phpstorm-plugin#1224 …
=> 1224: Fixed compatibility issues by updating icon constants

src/com/magento/idea/magento2uct/execution/configurations/UctRunConfiguration.java, src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.form, src/com/magento/idea/magento2uct/execution/configurations/UctSettingsEditor.java
Currently CLI UCT implementation uses hardcoded supported versions, which means it takes some time to add new version to the plugin codebase. This PR make able to run UCT for ever possible version. 
More details on what was done:
* Made editable combobox for coming version input.
* Custom coming version will be save in configuration, also it will be available as an option when user previously save it in config.
* Added regular expression (RegEx) to check a SemVer string for coming version input. User will see an error if format of version is incorrect.
* Fix additional issue related to command parameter - module path.
https://user-images.githubusercontent.com/20201927/203714053-55cfbcba-d615-4f8e-80b4-9ab675627e69.mov
**Questions or …
=> UCT custom coming versions

CHANGELOG.md, src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
Added check whether plugin PHP class exists before indexing it.
1. Fixes magento/magento2-phpstorm-plugin#1256
2. Fixes magento/magento2-phpstorm-plugin#1232
3. Fixes magento/magento2-phpstorm-plugin#1241
4. Fixes magento/magento2-phpstorm-plugin#1255
=> 1220: avoid indexing not existing plugin classes

CHANGELOG.md, resources/fileTemplates/internal/Magento Form Button Block Class.php.ft, src/com/magento/idea/magento2plugin/actions/generation/generator/UiComponentFormButtonBlockGenerator.java, testData/actions/generation/generator/FormButtonBlockGenerator/generateDeleteButtonBlock/DeleteBlock.php
Fixed issue with the visible delete button in the create new entity form.
1. Fixes magento/magento2-phpstorm-plugin#1226
=> 1226: fixed issue with visible delete button in the new entity form

CHANGELOG.md, src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleGraphQlResolverClassGenerator.java
Removed AWT events from write action
1. Fixes magento/magento2-phpstorm-plugin#1269
=> 1269: fixed AWT events are not allowed inside write action

CHANGELOG.md, src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java
=> 1215: fix parsing of plugin sort order value [backport 5.0.1]

resources/fileTemplates/internal/Magento Form Button Block Class.php.ft, src/com/magento/idea/magento2plugin/stubs/indexes/PluginIndex.java, testData/actions/generation/generator/FormButtonBlockGenerator/generateBackButtonBlock/MyBackButton.php, testData/actions/generation/generator/FormButtonBlockGenerator/generateCustomButtonBlock/MyCustom.php, testData/actions/generation/generator/FormButtonBlockGenerator/generateDeleteButtonBlock/DeleteBlock.php, testData/actions/generation/generator/FormButtonBlockGenerator/generateSaveButtonBlock/SaveBlock.php
1. Fixes magento/magento2-phpstorm-plugin#1277
=> 1277: fixed throwable and wrapButtonSettings function call

.github/workflows/gradle.yml, .github/workflows/gradlepublish.yml, .github/workflows/gradlepublishalpha.yml, README.md, build.gradle, resources/META-INF/plugin.xml, src/com/magento/idea/magento2plugin/actions/groups/NewEavAttributeGroup.java, src/com/magento/idea/magento2plugin/actions/groups/NewModuleFileGroup.java, src/com/magento/idea/magento2plugin/init/ConfigurationManager.java, tests/com/magento/idea/magento2plugin/linemarker/LinemarkerFixtureTestCase.java, tests/com/magento/idea/magento2plugin/linemarker/graphqls/GraphQlResolverClassLinemarkerRegistrarTest.java
=> 5.1.0 forwardport

CHANGELOG.md, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/DataPatchNameAdapter.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/event/eavdialog/SourceModelNameAdapter.java, tests/com/magento/idea/magento2plugin/linemarker/LinemarkerFixtureTestCase.java, tests/com/magento/idea/magento2plugin/linemarker/graphqls/GraphQlResolverClassLinemarkerRegistrarTest.java
Fixed reference to not existing util.
1. Fixes magento/magento2-phpstorm-plugin#1527
=> 1527: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/StringUtils fix

src/com/magento/idea/magento2plugin/actions/generation/dialog/NewDataModelDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewEntityDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewLayoutTemplateDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewMessageQueueDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewObserverDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentFormDialog.java, src/com/magento/idea/magento2plugin/actions/generation/dialog/NewUiComponentGridDialog.java
Added the ability to switch between files when creating files using the plugin
Changes have been made to files such as:
New Entity
New Layout
New Message Queue
New Observer
New Ui Component Form
New Ui Component Grid
For other files, this functionality is not needed
https://user-images.githubusercontent.com/43544955/219856373-1ac782b2-495b-4e33-9935-644cc166857e.mp4
=> Modal actions for generating files
